// packages/mochart-demo-angular/src/components/sparkline/demo-sparkline.ts
import { Component, Input, computed, signal } from '@angular/core';

import { DefaultChart } from '@mochart/angular';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';
import type { DataObject, SparklineMetric } from '@mochart/demo-common';

import { ButtonWithTooltip } from '../misc/button-with-tooltip';
import { Icon } from '../misc/icon';
import { TopBar } from '../misc/top-bar';

interface TableRow {
  metric: SparklineMetric;
  data: DataObject[];
  latest: string;
}

/**
 * The sparkline showcase page: the intro paragraph with word-sized charts
 * woven between the demoText.sparklinePage.intro segments, then the
 * small-multiples metrics table. Every chart mounts at the metric's explicit
 * width/height (no element sizing); Randomize bumps the step signal and the
 * computed datasets (and each row's latest text) follow.
 */
@Component({
  selector: 'app-demo-sparkline',
  imports: [DefaultChart, ButtonWithTooltip, Icon, TopBar],
  styles: [':host { display: contents; }'],
  template: `
    <div class="mochart-demo-container">
      <app-top-bar [siteRootUrl]="siteRootUrl" [onBackToDemos]="onBackToDemos" />
      <div class="sparkline-page">
        <p class="sparkline-intro">@for (segment of text.intro; track $index) {{{ segment }}@if (inlineMetrics[$index]; as metric) {<span class="sparkline-inline"><mochart-default-chart [config]="metric.config" [data]="inlineData()[$index]" [width]="metric.width" [height]="metric.height" /></span>}}</p>
        <div class="sparkline-controls">
          <app-button-with-tooltip id="sparkline-randomize" color="primary" [label]="text.randomize.label"
                                   [tooltipText]="text.randomize.tooltip" tooltipPlacement="top-start"
                                   [onClick]="onRandomize" [aria-label]="text.randomize.aria">
            <app-icon [fixedWidth]="true" name="dice" />
          </app-button-with-tooltip>
        </div>
        <table class="sparkline-table">
          <thead>
            <tr>
              <th>{{ text.table.metric }}</th>
              <th>{{ text.table.latest }}</th>
              <th>{{ text.table.trend }}</th>
            </tr>
          </thead>
          <tbody>
            @for (row of tableRows(); track row.metric.id) {
              <tr>
                <td>{{ row.metric.label }}</td>
                <td class="sparkline-value">{{ row.latest }}</td>
                <td class="sparkline-cell">
                  <mochart-default-chart [config]="row.metric.config" [data]="row.data"
                                         [width]="row.metric.width" [height]="row.metric.height" />
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class DemoSparkline {
  @Input() siteRootUrl?: string;
  @Input({ required: true }) onBackToDemos!: () => void;

  readonly text = demoText.sparklinePage;
  readonly inlineMetrics = inlineSparklineMetrics;

  readonly step = signal(0);

  readonly inlineData = computed<DataObject[][]>(() => {
    const step = this.step();
    return this.inlineMetrics.map(metric => metric.generate(step));
  });

  readonly tableRows = computed<TableRow[]>(() => {
    const step = this.step();
    return tableSparklineMetrics.map(metric => {
      const data = metric.generate(step);
      return { metric, data, latest: metric.latestText(data) };
    });
  });

  onRandomize = (): void => {
    this.step.update(step => step + 1);
  };
}

// packages/mochart-demo-lit/src/components/sparkline/demo-sparkline.ts
import { html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';

import { defaultChart } from '@mochart/lit';

import { demoText, inlineSparklineMetrics, tableSparklineMetrics } from '@mochart/demo-common';
import type { SparklineMetric } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';
import { buttonWithTooltip, icon } from '../misc/templates';
import '../misc/top-bar';

const text = demoText.sparklinePage;

@customElement('demo-sparkline')
export class DemoSparkline extends LightElement {
  @property({ attribute: false }) siteRootUrl: string | undefined = undefined;
  @property({ attribute: false }) onBackToDemos!: () => void;

  // Each Randomize click bumps the step; every chart's data (and each table
  // row's latest text) derives from it, so a re-render regenerates them all
  // and the binding's directive updates each mounted chart in place.
  @state() private step = 0;

  private onRandomize = (): void => {
    this.step++;
  };

  // Charts mount at the metric's explicit word/cell size, never auto-sized.
  private renderMetricChart(metric: SparklineMetric, data: ReturnType<SparklineMetric['generate']>): unknown {
    return defaultChart({ config: metric.config, data, width: metric.width, height: metric.height });
  }

  private renderIntro(): unknown {
    return html`<p class="sparkline-intro">${text.intro.map((segment, i) => {
      const metric = inlineSparklineMetrics[i];
      return html`${segment}${metric !== undefined
        ? html`<span class="sparkline-inline">${this.renderMetricChart(metric, metric.generate(this.step))}</span>`
        : nothing}`;
    })}</p>`;
  }

  private renderTableRow(metric: SparklineMetric): unknown {
    const data = metric.generate(this.step);
    return html`<tr>
      <td>${metric.label}</td>
      <td class="sparkline-value">${metric.latestText(data)}</td>
      <td class="sparkline-cell">${this.renderMetricChart(metric, data)}</td>
    </tr>`;
  }

  override render(): unknown {
    return html`<div class="mochart-demo-container">
      <top-bar .siteRootUrl=${this.siteRootUrl} .onBackToDemos=${this.onBackToDemos}></top-bar>
      <div class="sparkline-page">
        ${this.renderIntro()}
        <div class="sparkline-controls">
          ${buttonWithTooltip(
            { id: 'sparkline-randomize', label: text.randomize.label, tooltipText: text.randomize.tooltip, ariaLabel: text.randomize.aria, color: 'primary', onClick: this.onRandomize },
            icon({ fixedWidth: true, name: 'dice' })
          )}
        </div>
        <table class="sparkline-table">
          <thead>
            <tr>
              <th>${text.table.metric}</th>
              <th>${text.table.latest}</th>
              <th>${text.table.trend}</th>
            </tr>
          </thead>
          <tbody>
            ${tableSparklineMetrics.map(metric => this.renderTableRow(metric))}
          </tbody>
        </table>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'demo-sparkline': DemoSparkline;
  }
}
