// packages/mochart-demo-vue/src/components/rotation/DemoRotation.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';

import { DefaultChart } from '@mochart/vue';

import TopBar from '../misc/TopBar.vue';

import { getRotationGrid, rotationConfigs as configs, rotationData as data } from '@mochart/demo-common';

interface Props {
  siteRootUrl?: string;
  onBackToDemos: () => void;
}

const props = defineProps<Props>();

// Columns are sized from the card's measured width (not the window) so the
// grid stays inside the padded shell.
const chartsElement = ref<HTMLDivElement | null>(null);
const chartsWidth = ref(0);

let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  const el = chartsElement.value;
  if (el) {
    const measure = () => { chartsWidth.value = el.clientWidth; };
    resizeObserver = new ResizeObserver(measure);
    resizeObserver.observe(el);
    measure();
  }
});

onBeforeUnmount(() => {
  if (resizeObserver !== null) {
    resizeObserver.disconnect();
    resizeObserver = null;
  }
});

const grid = computed(() => getRotationGrid(chartsWidth.value));
const cols = computed(() => grid.value.cols);
const colWidth = computed(() => grid.value.colWidth);
</script>

<template>
  <div class="mochart-demo-container">
    <TopBar :site-root-url="props.siteRootUrl" :on-back-to-demos="props.onBackToDemos" />
    <div ref="chartsElement" class="rotation-charts">
      <template v-if="colWidth > 0">
        <div v-for="(config, i) in configs" :key="i"
             :class="'rotation-chart rotation-chart-' + i"
             :style="`left: ${(i % cols) * colWidth}px; top: ${Math.floor(i / cols) * colWidth}px; width: ${colWidth}px; height: ${colWidth}px;`">
          <DefaultChart :config="config" :data="data" :width="colWidth" :height="colWidth" />
        </div>
      </template>
    </div>
  </div>
</template>

// packages/mochart-demo-svelte/src/components/rotation/DemoRotation.svelte
<script module lang="ts">
  import { getRotationGrid, rotationConfigs as configs, rotationData as data } from '@mochart/demo-common';
</script>

<script lang="ts">
  import { DefaultChart } from '@mochart/svelte';

  import TopBar from '../misc/TopBar.svelte';

  interface Props {
    siteRootUrl?: string;
    onBackToDemos: () => void;
  }

  let { siteRootUrl = undefined, onBackToDemos }: Props = $props();

  // Columns are sized from the card's measured width (not the window) so the
  // grid stays inside the padded shell.
  let chartsWidth = $state(0);

  const grid = $derived(getRotationGrid(chartsWidth));
  const cols = $derived(grid.cols);
  const colWidth = $derived(grid.colWidth);
</script>

<div class="mochart-demo-container">
  <TopBar {siteRootUrl} {onBackToDemos} />
  <div class="rotation-charts" bind:clientWidth={chartsWidth}>
    {#if colWidth > 0}
      {#each configs as config, i (i)}
        <div class={"rotation-chart rotation-chart-" + i}
             style={`left: ${(i % cols) * colWidth}px; top: ${Math.floor(i / cols) * colWidth}px; width: ${colWidth}px; height: ${colWidth}px;`}>
          <DefaultChart {config} {data} width={colWidth} height={colWidth} />
        </div>
      {/each}
    {/if}
  </div>
</div>
