// packages/mochart-lit/src/placeholders.ts
import { nothing, render } from 'lit-html';
import type { PlaceholderProps, PlaceholderTemplate } from './types.js';

// Maps the wrapper's template props to the core's DOM-factory prop names.
const FACTORY_PROP_NAMES: Record<string, string> = {
  loadingTemplate: 'getLoadingComponent',
  errorTemplate: 'getErrorComponent',
  noDataTemplate: 'getNoDataComponent',
  noSizeTemplate: 'getNoSizeComponent',
  noSeriesTemplate: 'getNoSeriesComponent',
  configErrorTemplate: 'getConfigErrorComponent'
};

interface PlaceholderSlot {
  template: PlaceholderTemplate;
  /** The last context the core rendered this slot with; null until its first factory call. */
  context: PlaceholderProps | null;
  container: HTMLDivElement;
  /** Whether the container holds a rendered template; false once the core dropped the container from the chart. */
  rendered: boolean;
  factory: (context: PlaceholderProps) => Node;
}

export interface PlaceholderAdapter {
  transform(props: Record<string, any>): Record<string, any>;
  /** Watches the chart host so a slot the core detaches (chart left that state) renders nothing, disconnecting its directives, and one it re-attaches renders again; returns the stop function. */
  attach(host: Element): () => void;
  destroy(): void;
}

/**
 * Adapts placeholder template props into the DOM-node factories the core
 * expects: each slot keeps one persistent container div that templates are
 * rendered into, so repeat factory calls patch in place. The factory identity
 * is stable per slot; a template change (every host render, for an inline
 * template) flows through `transform` and re-renders a slot the core has
 * already rendered with its last context.
 */
export function createPlaceholderAdapter(): PlaceholderAdapter {
  const slots = new Map<string, PlaceholderSlot>();

  function renderSlot(slot: PlaceholderSlot, context: PlaceholderProps): Node {
    slot.context = context;
    slot.rendered = true;
    render(slot.template({ ...context }), slot.container);
    return slot.container;
  }

  // Renders nothing into the container, which disconnects the template's directives.
  function clearSlot(slot: PlaceholderSlot): void {
    if (slot.rendered) {
      slot.rendered = false;
      render(nothing, slot.container);
    }
  }

  /** The core only removes a slot's container when the chart leaves the state: the template goes with it, and re-entry renders it again, as React and Svelte do. */
  function syncAttached(slot: PlaceholderSlot, host: Element): void {
    // containment, not isConnected: a chart hosted in a detached tree still owns its placeholders
    const attached = host.contains(slot.container);
    if (!attached && slot.rendered) {
      clearSlot(slot);
    }
    else if (attached && !slot.rendered && slot.context !== null) {
      renderSlot(slot, slot.context);
    }
  }

  function getSlot(propName: string, template: PlaceholderTemplate): PlaceholderSlot {
    let slot = slots.get(propName);
    if (!slot) {
      const container = document.createElement('div');
      // The container is a neutral wrapper; the placeholder template owns layout.
      container.style.display = 'contents';
      slot = {
        template,
        context: null,
        container,
        rendered: false,
        factory: (context: PlaceholderProps) => renderSlot(slots.get(propName)!, context)
      };
      slots.set(propName, slot);
    }
    if (slot.template !== template) {
      slot.template = template;
      // the core's factory gate keys on the stable factory identity, so it would not re-run for this
      if (slot.context) {
        renderSlot(slot, slot.context);
      }
    }
    return slot;
  }

  // Clears a slot's rendered template (disconnecting its directives) and forgets it.
  function releaseSlot(propName: string): void {
    const slot = slots.get(propName);
    if (!slot) {
      return;
    }
    clearSlot(slot);
    slots.delete(propName);
  }

  return {
    transform(props: Record<string, any>): Record<string, any> {
      const out = { ...props };
      for (const propName of Object.keys(FACTORY_PROP_NAMES)) {
        const template = out[propName] as PlaceholderTemplate | undefined;
        delete out[propName];
        if (template) {
          out[FACTORY_PROP_NAMES[propName]] = getSlot(propName, template).factory;
        }
        else {
          // the chart falls back to its built-in placeholder, so nothing keeps this render alive
          releaseSlot(propName);
        }
      }
      return out;
    },
    attach(host: Element): () => void {
      if (typeof MutationObserver === 'undefined') {
        return () => {};
      }
      const observer = new MutationObserver(() => {
        for (const slot of slots.values()) {
          syncAttached(slot, host);
        }
      });
      observer.observe(host, { childList: true, subtree: true });
      return () => observer.disconnect();
    },
    destroy(): void {
      for (const propName of [...slots.keys()]) {
        releaseSlot(propName);
      }
    }
  };
}

// packages/mochart-react/src/placeholders.ts
import { createElement } from 'react';
import { createPortal } from 'react-dom';
import type { ReactPortal } from 'react';
import type { PlaceholderComponent, PlaceholderProps } from './types.js';

// Maps the wrapper's component props to the core's DOM-factory prop names.
const FACTORY_PROP_NAMES: Record<string, string> = {
  loadingComponent: 'getLoadingComponent',
  errorComponent: 'getErrorComponent',
  noDataComponent: 'getNoDataComponent',
  noSizeComponent: 'getNoSizeComponent',
  noSeriesComponent: 'getNoSeriesComponent',
  configErrorComponent: 'getConfigErrorComponent'
};

interface PlaceholderSlot {
  component: PlaceholderComponent;
  context: PlaceholderProps | null;
  container: HTMLDivElement;
  /** False once the core has dropped the container from the chart; the portal goes with it. */
  attached: boolean;
  factory: (context: PlaceholderProps) => Node;
}

export interface PlaceholderAdapter {
  transform(props: Record<string, any>): Record<string, any>;
  /** Watches the chart host so a slot the core detaches (chart left that state) unmounts its component; returns the stop function. */
  attach(host: Element): () => void;
  // property signatures: these are passed unbound to useSyncExternalStore
  subscribe: (listener: () => void) => () => void;
  getPortals: () => ReactPortal[];
}

/**
 * Adapts placeholder component props into the DOM-node factories the core
 * expects: each slot keeps one persistent container div the factory returns
 * synchronously, and the component renders into it through a portal from the
 * host tree — so placeholders inherit the host app's context providers. The
 * host subscribes and re-renders `getPortals()` whenever a slot changes.
 */
export function createPlaceholderAdapter(): PlaceholderAdapter {
  const slots = new Map<string, PlaceholderSlot>();
  const listeners = new Set<() => void>();
  let portals: ReactPortal[] = [];

  function notify(): void {
    portals = [];
    for (const [propName, slot] of slots) {
      if (slot.context && slot.attached) {
        portals.push(createPortal(createElement(slot.component, slot.context), slot.container, propName));
      }
    }
    for (const listener of listeners) {
      listener();
    }
  }

  function getSlot(propName: string, component: PlaceholderComponent): PlaceholderSlot {
    let slot = slots.get(propName);
    if (!slot) {
      const container = document.createElement('div');
      // The container is a neutral wrapper; the placeholder component owns layout.
      container.style.display = 'contents';
      slot = {
        component,
        context: null,
        container,
        attached: false,
        factory: (context: PlaceholderProps) => {
          const current = slots.get(propName)!;
          current.context = context;
          // the core appends the returned container right after this call
          current.attached = true;
          notify();
          return current.container;
        }
      };
      slots.set(propName, slot);
    }
    if (slot.component !== component) {
      slot.component = component;
      if (slot.context) {
        notify();
      }
    }
    return slot;
  }

  return {
    transform(props: Record<string, any>): Record<string, any> {
      const out = { ...props };
      for (const propName of Object.keys(FACTORY_PROP_NAMES)) {
        const component = out[propName] as PlaceholderComponent | undefined;
        delete out[propName];
        if (component) {
          out[FACTORY_PROP_NAMES[propName]] = getSlot(propName, component).factory;
        } else {
          const slot = slots.get(propName);
          if (slot?.context) {
            slot.context = null;
            notify();
          }
        }
      }
      return out;
    },
    attach(host: Element): () => void {
      if (typeof MutationObserver === 'undefined') {
        return () => {};
      }
      const observer = new MutationObserver(() => {
        let changed = false;
        for (const slot of slots.values()) {
          // containment, not isConnected: a chart hosted in a detached tree still owns its placeholders
          const attached = host.contains(slot.container);
          if (slot.context && attached !== slot.attached) {
            slot.attached = attached;
            changed = true;
          }
        }
        if (changed) {
          notify();
        }
      });
      observer.observe(host, { childList: true, subtree: true });
      return () => observer.disconnect();
    },
    subscribe(listener: () => void): () => void {
      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    },
    getPortals(): ReactPortal[] {
      return portals;
    }
  };
}
