// packages/mochart-demo-vue/src/components/rotation/DemoRotation.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';

import { DefaultChart } from '@mochart/vue';

import TopBar from '../misc/TopBar.vue';

import { getRotationGrid, rotationConfigs as configs, rotationData as data } from '@mochart/demo-common';

interface Props {
  siteRootUrl?: string;
  onBackToDemos: () => void;
}

const props = defineProps<Props>();

// Columns are sized from the card's measured width (not the window) so the
// grid stays inside the padded shell.
const chartsElement = ref<HTMLDivElement | null>(null);
const chartsWidth = ref(0);

let resizeObserver: ResizeObserver | null = null;

onMounted(() => {
  const el = chartsElement.value;
  if (el) {
    const measure = () => { chartsWidth.value = el.clientWidth; };
    resizeObserver = new ResizeObserver(measure);
    resizeObserver.observe(el);
    measure();
  }
});

onBeforeUnmount(() => {
  if (resizeObserver !== null) {
    resizeObserver.disconnect();
    resizeObserver = null;
  }
});

const grid = computed(() => getRotationGrid(chartsWidth.value));
const cols = computed(() => grid.value.cols);
const colWidth = computed(() => grid.value.colWidth);
</script>

<template>
  <div class="mochart-demo-container">
    <TopBar :site-root-url="props.siteRootUrl" :on-back-to-demos="props.onBackToDemos" />
    <div ref="chartsElement" class="rotation-charts">
      <template v-if="colWidth > 0">
        <div v-for="(config, i) in configs" :key="i"
             :class="'rotation-chart rotation-chart-' + i"
             :style="`left: ${(i % cols) * colWidth}px; top: ${Math.floor(i / cols) * colWidth}px; width: ${colWidth}px; height: ${colWidth}px;`">
          <DefaultChart :config="config" :data="data" :width="colWidth" :height="colWidth" />
        </div>
      </template>
    </div>
  </div>
</template>

// packages/mochart-demo-react/src/components/rotation/DemoRotation.tsx
import { getRotationGrid, rotationConfigs as configs, rotationData as data } from '@mochart/demo-common';

import React, { useState, useEffect, useRef } from 'react';

import { DefaultChart } from '@mochart/react';

import TopBar from '../misc/TopBar';

import type { OnBackToDemos } from '../../types';

interface DemoRotationProps {
  siteRootUrl?: string;
  onBackToDemos: OnBackToDemos;
}

export default function DemoRotation({ siteRootUrl, onBackToDemos }: DemoRotationProps) {
  // Columns are sized from the card's measured width (not the window) so the
  // grid stays inside the padded shell.
  const chartsRef = useRef<HTMLDivElement | null>(null);
  const [chartsWidth, setChartsWidth] = useState(0);

  useEffect(() => {
    const el = chartsRef.current;
    if (!el) {
      return;
    }
    const measure = () => setChartsWidth(el.clientWidth);
    const observer = new ResizeObserver(measure);
    observer.observe(el);
    measure();
    return () => observer.disconnect();
  }, []);

  const { cols, colWidth } = getRotationGrid(chartsWidth);

  return (
    <div className="mochart-demo-container">
      <TopBar siteRootUrl={siteRootUrl} onBackToDemos={onBackToDemos} />
      <div className="rotation-charts" ref={chartsRef}>
        {colWidth > 0 ? configs.map((config, i) => <DemoRotationChart key={i} data={data} config={config} i={i} cols={cols} colWidth={colWidth} />) : null}
      </div>
    </div>
  );
}

interface DemoRotationChartProps {
  data: Record<string, any>[];
  config: Record<string, any>;
  i: number;
  cols: number;
  colWidth: number;
}

function DemoRotationChart({ data, config, i, cols, colWidth }: DemoRotationChartProps) {
  const row = Math.floor(i / cols);

  const style: React.CSSProperties = {
    left: i % cols * colWidth,
    top: row * colWidth,
    width: colWidth,
    height: colWidth
  };

  return (
    <div className={"rotation-chart rotation-chart-" + i} style={style}>
      <DefaultChart config={config} data={data} width={colWidth} height={colWidth} />
    </div>
  );
}
