// packages/mochart-demo-svelte/src/components/random/DemoRandom.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  import { buildMochartDemoConfig, demoText } from '@mochart/demo-common';
  import type { SwitchableDemoMode } from '@mochart/demo-common';

  import RandomContent from './RandomContent.svelte';
  import DemoTabs from '../misc/DemoTabs.svelte';
  import TopBar from '../misc/TopBar.svelte';

  import type { DemoData } from '../../types';

  interface Props {
    demoData: DemoData;
    initialDemoId: string;
    siteRootUrl?: string;
    onModeChanged: (nextDemoMode: SwitchableDemoMode) => void;
    onBackToDemos: () => void;
    randomId: number;
    incrementRandomId: () => void;
    decrementRandomId: () => void;
  }

  const eventKeyChart = 1;
  const eventKeyConfig = 2;
  const eventKeyData = 3;

  let {
    demoData,
    initialDemoId,
    siteRootUrl = undefined,
    onModeChanged,
    onBackToDemos,
    randomId,
    incrementRandomId,
    decrementRandomId
  }: Props = $props();

  function buildStateForDemo(demoId: string) {
    const demo = demoData.demoObjectMap[demoId];
    return {
      mochartDemoConfig: buildMochartDemoConfig(demo.config),
      randomConfig: Object.assign({}, demo.random, { valid: true }),
      generator: demo.generator
    };
  }

  // Props intentionally seed local state with their initial value only; the
  // $effect.pre below re-syncs everything when the routed demo changes.
  // svelte-ignore state_referenced_locally
  const initialState = buildStateForDemo(initialDemoId);

  let activeKey = $state(eventKeyChart);
  let mochartDemoConfig = $state.raw(initialState.mochartDemoConfig);
  let randomConfig = $state.raw(initialState.randomConfig);
  let generator = $state.raw(initialState.generator);

  // svelte-ignore state_referenced_locally
  let previousInitialDemoId = initialDemoId;
  $effect.pre(() => {
    const nextInitialDemoId = initialDemoId;
    untrack(() => {
      if (nextInitialDemoId !== previousInitialDemoId) {
        previousInitialDemoId = nextInitialDemoId;
        const nextState = buildStateForDemo(nextInitialDemoId);
        activeKey = eventKeyChart;
        mochartDemoConfig = nextState.mochartDemoConfig;
        randomConfig = nextState.randomConfig;
        generator = nextState.generator;
      }
    });
  });

  function handleSelect(nextActiveKey: number) {
    activeKey = nextActiveKey;
  }
</script>

<div class="mochart-demo-container multi">
  <TopBar {siteRootUrl} {onBackToDemos}
          notes={demoData.demoObjectMap[initialDemoId]}
          modes={{ demoMode: 'random', onModeChanged }}>
    {#snippet tabs()}
      <DemoTabs {activeKey} onSelect={handleSelect}
                tabs={[
                  { name: 'chart', key: eventKeyChart, label: demoText.tabs.chart },
                  { name: 'config', key: eventKeyConfig, label: demoText.tabs.randomConfig },
                  { name: 'data', key: eventKeyData, label: demoText.tabs.data }
                ]} />
    {/snippet}
  </TopBar>
  <div class="mochart-demo-content-pane">
    <RandomContent {mochartDemoConfig} initialRandomConfig={randomConfig} {generator}
                   {activeKey} eventKeys={{ eventKeyChart, eventKeyConfig, eventKeyData }}
                   {randomId} {incrementRandomId} {decrementRandomId} />
  </div>
</div>

// packages/mochart-demo-vue/src/components/random/DemoRandom.vue
<script setup lang="ts">
import { ref, shallowRef, watch } from 'vue';

import { buildMochartDemoConfig, demoText } from '@mochart/demo-common';
import type { SwitchableDemoMode } from '@mochart/demo-common';

import DemoTabs from '../misc/DemoTabs.vue';
import TopBar from '../misc/TopBar.vue';
import RandomContent from './RandomContent.vue';

import type { DemoData } from '../../types';

interface Props {
  demoData: DemoData;
  initialDemoId: string;
  siteRootUrl?: string;
  onModeChanged: (nextDemoMode: SwitchableDemoMode) => void;
  onBackToDemos: () => void;
  randomId: number;
  incrementRandomId: () => void;
  decrementRandomId: () => void;
}

const eventKeyChart = 1;
const eventKeyConfig = 2;
const eventKeyData = 3;

const props = defineProps<Props>();

function buildStateForDemo(demoId: string) {
  const demo = props.demoData.demoObjectMap[demoId];
  return {
    mochartDemoConfig: buildMochartDemoConfig(demo.config),
    randomConfig: Object.assign({}, demo.random, { valid: true }),
    generator: demo.generator
  };
}

const initialState = buildStateForDemo(props.initialDemoId);

const activeKey = ref(eventKeyChart);
const mochartDemoConfig = shallowRef(initialState.mochartDemoConfig);
const randomConfig = shallowRef(initialState.randomConfig);
const generator = shallowRef(initialState.generator);

// When the routed demo changes, rebuild its config state (RandomContent's own
// watch tells a demo change apart from a randomId-only step).
watch(() => props.initialDemoId, (nextInitialDemoId) => {
  const nextState = buildStateForDemo(nextInitialDemoId);
  activeKey.value = eventKeyChart;
  mochartDemoConfig.value = nextState.mochartDemoConfig;
  randomConfig.value = nextState.randomConfig;
  generator.value = nextState.generator;
});

function handleSelect(nextActiveKey: number) {
  activeKey.value = nextActiveKey;
}
</script>

<template>
  <div class="mochart-demo-container multi">
    <TopBar :site-root-url="props.siteRootUrl" :on-back-to-demos="props.onBackToDemos"
            :notes="props.demoData.demoObjectMap[props.initialDemoId]"
            :modes="{ demoMode: 'random', onModeChanged: props.onModeChanged }">
      <template #tabs>
        <DemoTabs :active-key="activeKey" :on-select="handleSelect"
                  :tabs="[
                    { name: 'chart', key: eventKeyChart, label: demoText.tabs.chart },
                    { name: 'config', key: eventKeyConfig, label: demoText.tabs.randomConfig },
                    { name: 'data', key: eventKeyData, label: demoText.tabs.data }
                  ]" />
      </template>
    </TopBar>
    <div class="mochart-demo-content-pane">
      <RandomContent :mochart-demo-config="mochartDemoConfig" :initial-random-config="randomConfig" :generator="generator"
                     :active-key="activeKey" :event-keys="{ eventKeyChart, eventKeyConfig, eventKeyData }"
                     :random-id="props.randomId" :increment-random-id="props.incrementRandomId" :decrement-random-id="props.decrementRandomId" />
    </div>
  </div>
</template>
