// packages/mochart-demo-lit/src/components/random/random-content.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { PropertyValues } from 'lit';

import { getDataErrors } from '@mochart/core';

import { LightElement } from '../misc/LightElement';
import './random-chart-tab';
import './random-config-tab';
import './random-data-tab';
import '../misc/error-tab';

import { consumeShareState, createErrorDataProvider, demoText, generateDemoDataProvider, getRandomDataObjects, neutralizeRandomReuse, restoreSharedRandomConfig } from '@mochart/demo-common';

import type { MochartDemoConfig, RandomConfigWithValid, DemoDataProvider } from '../../types';

interface EventKeys {
  eventKeyChart: number;
  eventKeyConfig: number;
  eventKeyData: number;
}

@customElement('random-content')
export class RandomContent extends LightElement {
  @property({ attribute: false }) mochartDemoConfig!: MochartDemoConfig;
  @property({ attribute: false }) initialRandomConfig!: RandomConfigWithValid;
  @property({ attribute: false }) generator: string | undefined = undefined;
  @property({ attribute: false }) activeKey = 0;
  @property({ attribute: false }) eventKeys!: EventKeys;
  @property({ attribute: false }) randomId = 0;
  @property({ attribute: false }) incrementRandomId!: () => void;
  @property({ attribute: false }) decrementRandomId!: () => void;

  @state() private randomConfig!: RandomConfigWithValid;
  @state() private dataProvider: DemoDataProvider | null = null;
  @state() private data: unknown = null;
  // Reuse defaults on to match the generator's historical behavior (the
  // config's reuse settings were always applied before the toggle worked).
  @state() private applyReuse = true;
  // Restored from a share link (the interval seeds the chart tab's rate);
  // undefined for a normal mount, where the default rate applies.
  private initialRate: number | undefined = undefined;

  private toggleApplyReuse = (): void => {
    this.applyReuse = !this.applyReuse;
    this.updateDataProvider();
  };

  private updateDataProvider(forcedRandomConfig?: RandomConfigWithValid): void {
    const { mochartConfig } = this.mochartDemoConfig;
    const nextRandomConfig = forcedRandomConfig !== undefined ? forcedRandomConfig : this.randomConfig;

    if (nextRandomConfig.valid) {
      // with reuse off the generator gets a config whose reuse settings are
      // neutralized, so every dataset is generated independently
      const generatorConfig = this.applyReuse ? nextRandomConfig : neutralizeRandomReuse(nextRandomConfig);
      const nextDataProvider = generateDemoDataProvider(this.generator, mochartConfig, generatorConfig, this.randomId);
      const { categoryValues = [], seriesValues = {} } = nextDataProvider;
      const nextData = getRandomDataObjects(mochartConfig, categoryValues, seriesValues);
      const dataErrors = getDataErrors(mochartConfig, nextDataProvider);
      if (dataErrors.length > 0) {
        console.error('data errors: ', dataErrors);
        console.warn('category values: ', categoryValues);
        console.warn('series values: ', seriesValues);
        this.dataProvider = createErrorDataProvider(demoText.errors.creatingDataProvider);
        this.data = { error: demoText.errors.creatingDataProvider };
        this.randomConfig = nextRandomConfig;
      }
      else {
        this.dataProvider = nextDataProvider;
        this.data = nextData;
        this.randomConfig = nextRandomConfig;
      }
    }
    else {
      this.dataProvider = createErrorDataProvider(demoText.errors.invalidRandomConfig);
      this.data = {
        error: demoText.errors.invalidRandomConfig
      };
      this.randomConfig = nextRandomConfig;
    }
  }

  override willUpdate(changed: PropertyValues<this>): void {
    if (!this.hasUpdated) {
      // A share link restores the generator config, reuse toggle and interval
      // (the step comes from the randomId in the URL path). Consume it once.
      const shared = consumeShareState('random');
      const sharedRandom = shared && shared.mode === 'random' ? shared : null;
      if (sharedRandom) {
        this.applyReuse = sharedRandom.applyReuse;
        this.initialRate = sharedRandom.interval;
        const restored: RandomConfigWithValid = restoreSharedRandomConfig(sharedRandom.randomConfig, this.generator);
        this.randomConfig = restored;
        this.updateDataProvider(restored);
      }
      else {
        this.randomConfig = this.initialRandomConfig;
        this.updateDataProvider(this.initialRandomConfig);
      }
      return;
    }
    // A demo change arrives as new config objects (and resets the random
    // config); a randomId-only change regenerates from the edited config.
    if (changed.has('initialRandomConfig') || changed.has('mochartDemoConfig')) {
      this.updateDataProvider(this.initialRandomConfig);
    }
    else if (changed.has('randomId')) {
      this.updateDataProvider();
    }
  }

  private onRandomizeBack = (): void => {
    this.decrementRandomId();
  };

  private onRandomizeNext = (): void => {
    this.incrementRandomId();
  };

  // Regenerate immediately so Apply/Reset on the Random Config tab visibly
  // take effect instead of waiting for the next randomize.
  private onUpdateConfig = (nextRandomConfig: RandomConfigWithValid): void => {
    this.updateDataProvider(nextRandomConfig);
  };

  private onResetConfig = (): void => {
    this.updateDataProvider(this.initialRandomConfig);
  };

  override render(): unknown {
    const { eventKeyChart, eventKeyConfig, eventKeyData } = this.eventKeys;
    return html`<div class="mochart-demo-content">
      <error-tab .active=${this.activeKey === eventKeyChart} .content=${() =>
        html`<random-chart-tab .active=${this.activeKey === eventKeyChart} .mochartConfig=${this.mochartDemoConfig.mochartConfig} .dataProvider=${this.dataProvider}
            .randomConfig=${this.randomConfig} .initialRate=${this.initialRate}
            .onRandomizeBack=${this.onRandomizeBack} .onRandomizeNext=${this.onRandomizeNext}
            .applyReuse=${this.applyReuse} .toggleApplyReuse=${this.toggleApplyReuse}></random-chart-tab>`}></error-tab>
      <error-tab .active=${this.activeKey === eventKeyConfig} .content=${() =>
        html`<random-config-tab .active=${this.activeKey === eventKeyConfig} .randomConfig=${this.randomConfig} .generator=${this.generator} .onUpdate=${this.onUpdateConfig} .onReset=${this.onResetConfig}></random-config-tab>`}></error-tab>
      <error-tab .active=${this.activeKey === eventKeyData} .content=${() =>
        html`<random-data-tab .active=${this.activeKey === eventKeyData} .data=${this.data}></random-data-tab>`}></error-tab>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'random-content': RandomContent;
  }
}

// packages/mochart-demo-vue/src/components/random/RandomContent.vue
<script setup lang="ts">
import { ref, shallowRef, watch } from 'vue';

import { getDataErrors } from '@mochart/core';

import RandomChartTab from './RandomChartTab.vue';
import RandomConfigTab from './RandomConfigTab.vue';
import RandomDataTab from './RandomDataTab.vue';
import ErrorTab from '../misc/ErrorTab.vue';

import { consumeShareState, createErrorDataProvider, demoText, generateDemoDataProvider, getRandomDataObjects, neutralizeRandomReuse, restoreSharedRandomConfig } from '@mochart/demo-common';

import type { MochartDemoConfig, RandomConfigWithValid, DemoDataProvider } from '../../types';

interface EventKeys {
  eventKeyChart: number;
  eventKeyConfig: number;
  eventKeyData: number;
}

interface Props {
  mochartDemoConfig: MochartDemoConfig;
  initialRandomConfig: RandomConfigWithValid;
  /** The demo's chart-type generator id, if it has one (demos.json). */
  generator?: string;
  activeKey: number;
  eventKeys: EventKeys;
  randomId: number;
  incrementRandomId: () => void;
  decrementRandomId: () => void;
}

const props = defineProps<Props>();

const { eventKeyChart, eventKeyConfig, eventKeyData } = props.eventKeys;

// A share link restores the generator config, reuse toggle and interval (the
// step comes from the randomId in the URL path). Consume it once at mount.
const sharedState = consumeShareState('random');
const initialShared = sharedState && sharedState.mode === 'random' ? sharedState : null;
const initialRate = initialShared ? initialShared.interval : undefined;

const randomConfig = shallowRef<RandomConfigWithValid>(
  initialShared ? restoreSharedRandomConfig(initialShared.randomConfig, props.generator) : props.initialRandomConfig);
const dataProvider = shallowRef<DemoDataProvider | null>(null);
const data = shallowRef<unknown>(null);
// Reuse defaults on to match the generator's historical behavior (the
// config's reuse settings were always applied before the toggle worked).
const applyReuse = ref(initialShared ? initialShared.applyReuse : true);

function toggleApplyReuse() {
  applyReuse.value = !applyReuse.value;
  updateDataProvider();
}

function updateDataProvider(forcedRandomConfig?: RandomConfigWithValid) {
  const { mochartConfig } = props.mochartDemoConfig;
  const nextRandomConfig = forcedRandomConfig !== undefined ? forcedRandomConfig : randomConfig.value;

  if (nextRandomConfig.valid) {
    // with reuse off the generator gets a config whose reuse settings are
    // neutralized, so every dataset is generated independently
    const generatorConfig = applyReuse.value ? nextRandomConfig : neutralizeRandomReuse(nextRandomConfig);
    const nextDataProvider = generateDemoDataProvider(props.generator, mochartConfig, generatorConfig, props.randomId);
    const { categoryValues = [], seriesValues = {} } = nextDataProvider;
    const nextData = getRandomDataObjects(mochartConfig, categoryValues, seriesValues);
    const dataErrors = getDataErrors(mochartConfig, nextDataProvider);
    if (dataErrors.length > 0) {
      console.error('data errors: ', dataErrors);
      console.warn('category values: ', categoryValues);
      console.warn('series values: ', seriesValues);
      dataProvider.value = createErrorDataProvider(demoText.errors.creatingDataProvider);
      data.value = { error: demoText.errors.creatingDataProvider };
      randomConfig.value = nextRandomConfig;
    }
    else {
      dataProvider.value = nextDataProvider;
      data.value = nextData;
      randomConfig.value = nextRandomConfig;
    }
  }
  else {
    dataProvider.value = createErrorDataProvider(demoText.errors.invalidRandomConfig);
    data.value = {
      error: demoText.errors.invalidRandomConfig
    };
    randomConfig.value = nextRandomConfig;
  }
}

updateDataProvider(randomConfig.value);

watch(
  () => [props.initialRandomConfig, props.mochartDemoConfig, props.randomId] as const,
  ([nextInitialRandomConfig, nextMochartDemoConfig, nextRandomId],
   [previousInitialRandomConfig, previousMochartDemoConfig, previousRandomId]) => {
    if (nextInitialRandomConfig !== previousInitialRandomConfig ||
        nextMochartDemoConfig !== previousMochartDemoConfig) {
      updateDataProvider(nextInitialRandomConfig);
    }
    else if (nextRandomId !== previousRandomId) {
      updateDataProvider();
    }
  }
);

function onRandomizeBack() {
  props.decrementRandomId();
}

function onRandomizeNext() {
  props.incrementRandomId();
}

// Regenerate immediately so Apply/Reset on the Random Config tab visibly
// take effect instead of waiting for the next randomize.
function onUpdateConfig(nextRandomConfig: RandomConfigWithValid) {
  updateDataProvider(nextRandomConfig);
}

function onResetConfig() {
  updateDataProvider(props.initialRandomConfig);
}
</script>

<template>
  <div class="mochart-demo-content">
    <ErrorTab :active="props.activeKey === eventKeyChart">
      <RandomChartTab :active="props.activeKey === eventKeyChart" :mochart-config="props.mochartDemoConfig.mochartConfig" :data-provider="dataProvider"
                      :random-config="randomConfig" :initial-rate="initialRate"
                      :on-randomize-back="onRandomizeBack" :on-randomize-next="onRandomizeNext"
                      :apply-reuse="applyReuse" :toggle-apply-reuse="toggleApplyReuse" />
    </ErrorTab>
    <ErrorTab :active="props.activeKey === eventKeyConfig">
      <RandomConfigTab :active="props.activeKey === eventKeyConfig" :random-config="randomConfig" :generator="props.generator" :on-update="onUpdateConfig" :on-reset="onResetConfig" />
    </ErrorTab>
    <ErrorTab :active="props.activeKey === eventKeyData">
      <RandomDataTab :active="props.activeKey === eventKeyData" :data="data" />
    </ErrorTab>
  </div>
</template>
