// packages/mochart-demo-lit/src/components/random/random-data-tab.ts
import { demoText, formatData, getDemoTabPanelAttrs } from '@mochart/demo-common';

import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { PropertyValues } from 'lit';

import { LightElement } from '../misc/LightElement';
import '../misc/json-editor-content';

const panelAttrs = getDemoTabPanelAttrs('data');

@customElement('random-data-tab')
export class RandomDataTab extends LightElement {
  @property({ attribute: false }) active = false;
  @property({ attribute: false }) data: unknown = null;

  @state() private dataText = '';

  override willUpdate(changed: PropertyValues<this>): void {
    if (changed.has('data')) {
      this.dataText = formatData(this.data);
    }
  }

  override render(): unknown {
    return html`<div id=${panelAttrs.id} role=${panelAttrs.role} aria-labelledby=${panelAttrs['aria-labelledby']}
        class=${'mochart-demo-tab-container demo-layout-col data' + (this.active ? ' active' : '')} ?inert=${!this.active}>
      <div class="mochart-demo-tab-content">
        <json-editor-content .value=${this.dataText} .ariaLabelText=${demoText.randomDataTab.editorAria} .readOnly=${true}></json-editor-content>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'random-data-tab': RandomDataTab;
  }
}

// packages/mochart-demo-angular/src/components/random/random-data-tab.ts
import { demoText, formatData, getDemoTabPanelAttrs } from '@mochart/demo-common';

import { Component, Input, signal } from '@angular/core';
import type { OnChanges, OnInit, SimpleChanges } from '@angular/core';

import { JsonEditorContent } from '../misc/json-editor-content';

@Component({
  selector: 'app-random-data-tab',
  imports: [JsonEditorContent],
  styles: [':host { display: contents; }'],
  template: `
    <div [id]="panelAttrs.id" [attr.role]="panelAttrs.role" [attr.aria-labelledby]="panelAttrs['aria-labelledby']"
         [class]="'mochart-demo-tab-container demo-layout-col data' + (active ? ' active' : '')" [attr.inert]="active ? null : ''">
      <div class="mochart-demo-tab-content">
        <app-json-editor-content [value]="dataText()" [ariaLabel]="text.editorAria" [readOnly]="true" />
      </div>
    </div>
  `
})
export class RandomDataTab implements OnInit, OnChanges {
  readonly panelAttrs = getDemoTabPanelAttrs('data');

  @Input() active = false;
  @Input({ required: true }) data: unknown;

  readonly text = demoText.randomDataTab;

  dataText = signal('');

  ngOnInit(): void {
    this.dataText.set(formatData(this.data));
  }

  ngOnChanges(changes: SimpleChanges): void {
    const dataChange = changes['data'];
    if (dataChange && !dataChange.firstChange) {
      this.dataText.set(formatData(this.data));
    }
  }
}
