// packages/mochart-demo-svelte/src/components/transition/TransitionChartTab.svelte
<script lang="ts">
  import { untrack } from 'svelte';

  import { Chart } from '@mochart/svelte';
  import type { MochartConfig } from '@mochart/core';

  import { demoText, getDemoTabPanelAttrs } from '@mochart/demo-common';

  import ButtonWithTooltip from '../misc/ButtonWithTooltip.svelte';
  import Icon from '../misc/Icon.svelte';

  import type { ChartDataProviderLike } from '../../types';

  interface Props {
    active?: boolean;
    mochartConfig: MochartConfig;
    dataProviders: ChartDataProviderLike[];
  }

  let { active = false, mochartConfig, dataProviders }: Props = $props();

  let dataProviderIndex = $state(0);

  // Props intentionally seed the previous-value snapshots with their initial
  // value only; the $effect.pre below re-syncs on later prop changes.
  // svelte-ignore state_referenced_locally
  let previousMochartConfig = mochartConfig;
  // svelte-ignore state_referenced_locally
  let previousDataProviders = dataProviders;
  $effect.pre(() => {
    const nextMochartConfig = mochartConfig;
    const nextDataProviders = dataProviders;
    untrack(() => {
      if (nextMochartConfig !== previousMochartConfig || nextDataProviders !== previousDataProviders) {
        previousMochartConfig = nextMochartConfig;
        previousDataProviders = nextDataProviders;
        dataProviderIndex = 0;
      }
    });
  });

  function onStepBack() {
    if (dataProviders.length > 1) {
      if (dataProviderIndex === 0) {
        dataProviderIndex = dataProviders.length - 1;
      }
      else {
        dataProviderIndex--;
      }
    }
  }

  function onStepForward() {
    if (dataProviders.length > 1) {
      if (dataProviderIndex === dataProviders.length - 1) {
        dataProviderIndex = 0;
      }
      else {
        dataProviderIndex++;
      }
    }
  }
</script>

<div {...getDemoTabPanelAttrs('chart')} class={"mochart-demo-tab-container demo-layout-col chart" + (active ? " active" : "")} inert={!active}>
  <div class="transition-chart-sizer">
    <Chart style="flex: 1 1 auto; min-width: 0; min-height: 0; overflow: hidden;"
           {mochartConfig} dataProvider={dataProviders[dataProviderIndex]} />
  </div>
  <div class="transition-controls">
    <form>
      <div class="demo-field">
        <div class="demo-toolbar">
          <div class="demo-btn-group">
            <ButtonWithTooltip id="transition-back" label={demoText.transitionChartTab.back.label} tooltipText={demoText.transitionChartTab.back.tooltip} tooltipPlacement="top-start"
                               onClick={onStepBack} aria-label={demoText.transitionChartTab.back.aria}>
              <Icon size="lg" fixedWidth={true} name="backward-step" />
            </ButtonWithTooltip>
            <ButtonWithTooltip id="transition-forward" label={demoText.transitionChartTab.next.label} tooltipText={demoText.transitionChartTab.next.tooltip} tooltipPlacement="top-start"
                               onClick={onStepForward} aria-label={demoText.transitionChartTab.next.aria}>
              <Icon size="lg" fixedWidth={true} name="forward-step" />
            </ButtonWithTooltip>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

// packages/mochart-demo-vue/src/components/transition/TransitionChartTab.vue
<script setup lang="ts">
import { ref, watch } from 'vue';

import { Chart } from '@mochart/vue';
import type { MochartConfig } from '@mochart/core';

import { demoText, getDemoTabPanelAttrs } from '@mochart/demo-common';

import ButtonWithTooltip from '../misc/ButtonWithTooltip.vue';
import Icon from '../misc/Icon.vue';

import type { ChartDataProviderLike } from '../../types';

interface Props {
  active?: boolean;
  mochartConfig: MochartConfig;
  dataProviders: ChartDataProviderLike[];
}

const props = withDefaults(defineProps<Props>(), {
  active: false
});

const dataProviderIndex = ref(0);

watch(() => [props.mochartConfig, props.dataProviders] as const, () => {
  dataProviderIndex.value = 0;
});

function onStepBack() {
  if (props.dataProviders.length > 1) {
    if (dataProviderIndex.value === 0) {
      dataProviderIndex.value = props.dataProviders.length - 1;
    }
    else {
      dataProviderIndex.value--;
    }
  }
}

function onStepForward() {
  if (props.dataProviders.length > 1) {
    if (dataProviderIndex.value === props.dataProviders.length - 1) {
      dataProviderIndex.value = 0;
    }
    else {
      dataProviderIndex.value++;
    }
  }
}

const panelAttrs = getDemoTabPanelAttrs('chart');
</script>

<template>
  <div v-bind="panelAttrs" :class="'mochart-demo-tab-container demo-layout-col chart' + (props.active ? ' active' : '')" :inert="!props.active">
    <div class="transition-chart-sizer">
      <Chart style="flex: 1 1 auto; min-width: 0; min-height: 0; overflow: hidden;"
             :mochart-config="props.mochartConfig" :data-provider="props.dataProviders[dataProviderIndex]" />
    </div>
    <div class="transition-controls">
      <form>
        <div class="demo-field">
          <div class="demo-toolbar">
            <div class="demo-btn-group">
              <ButtonWithTooltip id="transition-back" :label="demoText.transitionChartTab.back.label" :tooltip-text="demoText.transitionChartTab.back.tooltip" tooltip-placement="top-start"
                                 :on-click="onStepBack" :aria-label="demoText.transitionChartTab.back.aria">
                <Icon size="lg" :fixed-width="true" name="backward-step" />
              </ButtonWithTooltip>
              <ButtonWithTooltip id="transition-forward" :label="demoText.transitionChartTab.next.label" :tooltip-text="demoText.transitionChartTab.next.tooltip" tooltip-placement="top-start"
                                 :on-click="onStepForward" :aria-label="demoText.transitionChartTab.next.aria">
                <Icon size="lg" :fixed-width="true" name="forward-step" />
              </ButtonWithTooltip>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>
