// packages/mochart-demo-svelte/src/components/multi/ChartsTab.svelte
<script lang="ts">
  import { untrack, onDestroy } from 'svelte';

  import { Chart } from '@mochart/svelte';
  import { exportChartsPNG, exportChartsSVG } from '@mochart/export';

  import { getChartExportOptions, buildMochartDemoConfig, consumeShareState, getDataProvidersForDataCount, getPieSlices, getPieStepCycle, getPieStepFilteredIds, applyReportedSeriesFilter } from '@mochart/demo-common';
  import type { ShareState } from '@mochart/demo-common';

  import ChartsControls from './ChartsControls.svelte';

  import type { Demo, FilteredSeriesIds, ChartDataProviderLike } from '../../types';

  interface Props {
    demoObject: Demo;
    active?: boolean;
  }

  const scrollWidthOffset = 20;

  const defaultChartRows = 2;
  const defaultChartCols = 2;

  const defaultRate = 2000;

  let { demoObject, active = false }: Props = $props();

  let intervalId: ReturnType<typeof setInterval> | null = null;
  let gridElement = $state<HTMLDivElement | null>(null);

  // A share link restores the grid size, playback step and interval; otherwise
  // start on the defaults / full data set.
  const sharedState = consumeShareState('multi');
  const shared = sharedState && sharedState.mode === 'multi' ? sharedState : null;

  const initialChartRows = shared ? shared.rows : defaultChartRows;
  const initialChartCols = shared ? shared.cols : defaultChartCols;
  const initialRate = shared ? shared.interval : defaultRate;

  let playing = $state(false);
  let chartRows = $state(initialChartRows);
  let chartCols = $state(initialChartCols);
  let rate = $state(initialRate);
  // Props intentionally seed local state with their initial value only; the
  // $effect.pre below re-syncs everything when the demo changes.
  // svelte-ignore state_referenced_locally
  let mochartDemoConfig = $state.raw(buildMochartDemoConfig(demoObject.config));
  // svelte-ignore state_referenced_locally
  let data = $state.raw(demoObject.data);
  // svelte-ignore state_referenced_locally
  let dataCount = $state(demoObject.data.length);
  // Pie mode steps a filtering pattern instead of data prefixes: chart i at
  // step s filters the last (s + i) mod cycle slices, so the grid shows
  // different-sized views of the same pie and stepping animates all charts.
  // svelte-ignore state_referenced_locally
  let sliceIds = $state.raw(mochartDemoConfig.pieMode ? getPieSlices(mochartDemoConfig.mochartConfig).map(slice => slice.id) : []);
  const stepCycle = () => mochartDemoConfig.pieMode ? getPieStepCycle(sliceIds) : dataCount;
  // A shared step seeks the playback position; otherwise start on the full set
  // (pie mode starts at step 0, the grid's staggered initial view).
  // svelte-ignore state_referenced_locally
  let currentDataCount = $state(shared && stepCycle() > 0
    ? ((Math.round(shared.step) % stepCycle()) + stepCycle()) % stepCycle()
    : (mochartDemoConfig.pieMode ? 0 : demoObject.data.length));
  // svelte-ignore state_referenced_locally
  let dataProviders = $state.raw(getDataProvidersForDataCount(demoObject.data, initialChartRows * initialChartCols, currentDataCount));
  // svelte-ignore state_referenced_locally
  let focusedCategoryIndices = $state.raw<number[]>(dataProviders.map(() => -1));
  let focusedCategoryIndex = $state(-1);
  let focusedValueAxisId = $state.raw<string | null>(null);
  let focusedSeriesId = $state.raw<string | null>(null);
  let filteredSeriesIds = $state.raw<FilteredSeriesIds>({});

  function initFocusAndFiltered() {
    focusedCategoryIndex = -1;
    focusedValueAxisId = null;
    focusedSeriesId = null;
    filteredSeriesIds = {};
  }

  // svelte-ignore state_referenced_locally
  let previousDemoObject = demoObject;
  // svelte-ignore state_referenced_locally
  let previousActive = active;
  $effect.pre(() => {
    const nextDemoObject = demoObject;
    const nextActive = active;
    untrack(() => {
      if (nextDemoObject !== previousDemoObject) {
        previousDemoObject = nextDemoObject;
        mochartDemoConfig = buildMochartDemoConfig(nextDemoObject.config);
        initFocusAndFiltered();
        playing = false;
        data = nextDemoObject.data;
        dataCount = data.length;
        sliceIds = mochartDemoConfig.pieMode ? getPieSlices(mochartDemoConfig.mochartConfig).map(slice => slice.id) : [];
        currentDataCount = resetStep();
        dataProviders = getDataProvidersForDataCount(data, chartRows * chartCols, currentDataCount);
        focusedCategoryIndices = dataProviders.map(() => -1);
      }
      if (nextActive !== previousActive) {
        previousActive = nextActive;
        onStopClick();
      }
    });
  });

  function onRateChange(nextRate: number) {
    rate = nextRate;
  }

  function resetStep(): number {
    return mochartDemoConfig.pieMode ? 0 : dataCount;
  }

  function onRowsChange(nextChartRows: number) {
    chartRows = nextChartRows;
    currentDataCount = resetStep();
    dataProviders = getDataProvidersForDataCount(data, chartRows * chartCols, currentDataCount);
    focusedCategoryIndices = getFocusedCategoryIndices(dataProviders);
  }

  function onColsChange(nextChartCols: number) {
    chartCols = nextChartCols;
    currentDataCount = resetStep();
    dataProviders = getDataProvidersForDataCount(data, chartRows * chartCols, currentDataCount);
    focusedCategoryIndices = getFocusedCategoryIndices(dataProviders);
  }

  function onStepBackwardClick() {
    const cycle = stepCycle();
    currentDataCount = mochartDemoConfig.pieMode
      ? (currentDataCount - 1 + cycle) % cycle
      : cycle + (currentDataCount - 1) % cycle;
    dataProviders = getDataProvidersForDataCount(data, chartRows * chartCols, currentDataCount);
    focusedCategoryIndices = getFocusedCategoryIndices(dataProviders);
  }

  function onStepForwardClick() {
    currentDataCount = (currentDataCount + 1) % stepCycle();
    dataProviders = getDataProvidersForDataCount(data, chartRows * chartCols, currentDataCount);
    focusedCategoryIndices = getFocusedCategoryIndices(dataProviders);
  }

  function getFocusedCategoryIndices(nextDataProviders: ChartDataProviderLike[]): number[] {
    const { mochartConfig } = mochartDemoConfig;
    if (focusedCategoryIndex >= 0) {
      const categoryValue = data[focusedCategoryIndex][mochartConfig.categoryAxis.property ?? ''];
      return getFocusedCategoryIndicesForValue(nextDataProviders, mochartConfig.categoryAxis.property ?? '', categoryValue);
    }
    else {
      return nextDataProviders.map(() => -1);
    }
  }

  function getFocusedCategoryIndicesForValue(nextDataProviders: ChartDataProviderLike[], categoryProperty: string, categoryValue: unknown): number[] {
    let count, i;
    return nextDataProviders.map(dataProvider => {
      let chartCategoryIndex = -1;
      const categoryValues = dataProvider.getPropertyValues(categoryProperty) ?? [];
      count = categoryValues.length;
      for (i = 0; i < count; i++) {
        if (categoryValues[i] === categoryValue) {
          chartCategoryIndex = i;
          break;
        }
      }
      return chartCategoryIndex;
    });
  }

  function onPlayBackwardClick() {
    playing = true;
    intervalId = setInterval(onStepBackwardClick, rate);
  }

  function onPlayForwardClick() {
    playing = true;
    intervalId = setInterval(onStepForwardClick, rate);
  }

  function onStopClick() {
    if (intervalId !== null) {
      clearInterval(intervalId);
    }
    intervalId = null;
    playing = false;
  }

  onDestroy(() => {
    if (intervalId !== null) {
      clearInterval(intervalId);
      intervalId = null;
    }
  });

  function onChartFocus(chartIndex: number, focusData: { focusedValueAxisId?: string | null; focusedSeriesId?: string | null; focusedCategoryIndex?: number }) {
    const { focusedValueAxisId: valueAxisId, focusedSeriesId: seriesId } = focusData;
    let categoryIndex = focusData.focusedCategoryIndex;
    const { mochartConfig } = mochartDemoConfig;
    let nextFocusedCategoryIndices = focusedCategoryIndices;
    if (categoryIndex !== undefined && categoryIndex >= 0) {
      const categoryValue = (dataProviders[chartIndex].getPropertyValues(mochartConfig.categoryAxis.property ?? '') ?? [])[categoryIndex];
      const count = data.length;
      for (let i = 0; i < count; i++) {
        if (data[i][mochartConfig.categoryAxis.property ?? ''] === categoryValue) {
          categoryIndex = i;
          break;
        }
      }
      if (categoryIndex !== focusedCategoryIndex) {
        nextFocusedCategoryIndices = getFocusedCategoryIndicesForValue(dataProviders, mochartConfig.categoryAxis.property ?? '', categoryValue);
      }
    }
    else if (focusedCategoryIndex >= 0) {
      nextFocusedCategoryIndices = dataProviders.map(() => -1);
    }
    if (categoryIndex !== undefined) {
      focusedCategoryIndex = categoryIndex;
    }
    if (valueAxisId !== undefined) {
      focusedValueAxisId = valueAxisId;
    }
    if (seriesId !== undefined) {
      focusedSeriesId = seriesId;
    }
    focusedCategoryIndices = nextFocusedCategoryIndices;
  }

  // Pie mode unions the stepper's per-chart filtering with the user's
  // legend filtering, so the legend stays interactive while stepping.
  function chartFilteredSeriesIds(i: number): FilteredSeriesIds {
    return mochartDemoConfig.pieMode
      ? { ...filteredSeriesIds, ...getPieStepFilteredIds(sliceIds, i, currentDataCount) }
      : filteredSeriesIds;
  }

  // The chart reports the whole union it was shown; keep only the user delta.
  function onSeriesFilter(chartIndex: number, { filteredSeriesIds: reported }: { filteredSeriesIds: FilteredSeriesIds }) {
    filteredSeriesIds = applyReportedSeriesFilter(filteredSeriesIds, chartFilteredSeriesIds(chartIndex), reported);
  }

  // The whole grid exports as one tiled image; share captures the grid size,
  // playback step and interval so the link restores the same view.
  function getChartContainers(): Element[] {
    return gridElement ? Array.from(gridElement.querySelectorAll('.multi-mochart-chart')) : [];
  }

  function onExportPng() {
    const containers = getChartContainers();
    if (containers.length > 0) {
      void exportChartsPNG(containers, { cols: chartCols, ...getChartExportOptions() });
    }
  }

  function onExportSvg() {
    const containers = getChartContainers();
    if (containers.length > 0) {
      exportChartsSVG(containers, { cols: chartCols, ...getChartExportOptions() });
    }
  }

  function getShareState(): ShareState {
    return { mode: 'multi', rows: chartRows, cols: chartCols, step: currentDataCount, interval: rate };
  }

  // Measured size of the charts grid.
  let gridWidth = $state(0);
  let gridHeight = $state(0);

  const chartWidth = $derived(Math.floor((gridWidth - scrollWidthOffset) / chartCols));
  const chartHeight = $derived(Math.floor(gridHeight / chartRows));
</script>

<div class={"mochart-demo-tab-container demo-layout-col chart" + (active ? " active" : "")} inert={!active}>
  <div class="multi-charts-sizer" bind:this={gridElement} bind:clientWidth={gridWidth} bind:clientHeight={gridHeight}>
    {#if gridWidth > 0}
      <div class="multi-charts">
        {#each dataProviders as dataProvider, i (i)}
          <div class="multi-mochart-chart">
            <Chart mochartConfig={mochartDemoConfig.mochartConfig} {dataProvider}
                   width={chartWidth} height={chartHeight}
                   filteredSeriesIds={chartFilteredSeriesIds(i)}
                   focusedCategoryIndex={focusedCategoryIndices[i] ?? -1}
                   focusedValueAxisId={focusedValueAxisId ?? null} focusedSeriesId={focusedSeriesId ?? null}
                   onSeriesFilter={(filterData) => onSeriesFilter(i, filterData)} onFocus={(focusData) => onChartFocus(i, focusData)} />
          </div>
        {/each}
      </div>
    {/if}
  </div>
  <ChartsControls {playing} initialRows={initialChartRows} initialCols={initialChartCols} {initialRate}
                  {onRowsChange} {onColsChange}
                  {onStepBackwardClick} {onStepForwardClick}
                  {onPlayBackwardClick} {onPlayForwardClick}
                  {onStopClick} {onRateChange}
                  exportPng={onExportPng} exportSvg={onExportSvg} {getShareState} />
</div>

// packages/mochart-demo-angular/src/components/multi/charts-tab.ts
import { Component, ElementRef, Input, ViewChild, signal } from '@angular/core';
import type { AfterViewInit, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';

import { Chart } from '@mochart/angular';
import { exportChartsPNG, exportChartsSVG } from '@mochart/export';

import { getChartExportOptions, buildMochartDemoConfig, consumeShareState, getDataProvidersForDataCount, getPieSlices, getPieStepCycle, getPieStepFilteredIds, applyReportedSeriesFilter } from '@mochart/demo-common';
import type { MultiShareState, ShareState } from '@mochart/demo-common';

import { ChartsControls } from './charts-controls';
import { createElementSize } from '../misc/element-size';

import type { Demo, DataObject, FilteredSeriesIds, ChartDataProviderLike, MochartDemoConfig } from '../../types';

const scrollWidthOffset = 20;

const defaultChartRows = 2;
const defaultChartCols = 2;

const defaultRate = 2000;

@Component({
  selector: 'app-charts-tab',
  imports: [Chart, ChartsControls],
  styles: [':host { display: contents; }'],
  template: `
    <div [class]="'mochart-demo-tab-container demo-layout-col chart' + (active ? ' active' : '')" [attr.inert]="active ? null : ''">
      <div #grid class="multi-charts-sizer">
        @if (gridWidth() > 0) {
          <div class="multi-charts">
            @for (dataProvider of dataProviders(); track $index; let i = $index) {
              <div class="multi-mochart-chart">
                <mochart-chart [mochartConfig]="mochartDemoConfig()!.mochartConfig" [dataProvider]="dataProvider"
                               [width]="chartWidth" [height]="chartHeight"
                               [filteredSeriesIds]="chartFilteredSeriesIds(i)" [focusedCategoryIndex]="focusedCategoryIndexAt(i)"
                               [focusedValueAxisId]="focusedValueAxisId()" [focusedSeriesId]="focusedSeriesId()"
                               (seriesFilter)="onSeriesFilter(i, $event)" (focusChange)="onChartFocus(i, $event)" />
              </div>
            }
          </div>
        }
      </div>
      <app-charts-controls [playing]="playing()" [onRowsChange]="onRowsChange" [onColsChange]="onColsChange"
                           [onStepBackwardClick]="onStepBackwardClick" [onStepForwardClick]="onStepForwardClick"
                           [onPlayBackwardClick]="onPlayBackwardClick" [onPlayForwardClick]="onPlayForwardClick"
                           [onStopClick]="onStopClick" [onRateChange]="onRateChange"
                           [initialRows]="chartRows()" [initialCols]="chartCols()" [initialRate]="rate()"
                           [exportPng]="onExportPng" [exportSvg]="onExportSvg" [getShareState]="getShareState" />
    </div>
  `
})
export class ChartsTab implements OnInit, OnChanges, AfterViewInit, OnDestroy {
  @Input({ required: true }) demoObject!: Demo;
  @Input() active = false;

  @ViewChild('grid', { static: true }) gridElement!: ElementRef<HTMLDivElement>;

  private intervalId: ReturnType<typeof setInterval> | null = null;

  playing = signal(false);
  chartRows = signal(defaultChartRows);
  chartCols = signal(defaultChartCols);
  rate = signal(defaultRate);
  mochartDemoConfig = signal<MochartDemoConfig | null>(null);
  data = signal<DataObject[]>([]);
  dataCount = signal(0);
  // Pie mode steps a filtering pattern instead of data prefixes: chart i at
  // step s filters the last (s + i) mod cycle slices, so the grid shows
  // different-sized views of the same pie and stepping animates all charts.
  sliceIds = signal<string[]>([]);
  currentDataCount = signal(0);
  dataProviders = signal<ChartDataProviderLike[]>([]);
  focusedCategoryIndices = signal<number[]>([]);
  focusedCategoryIndex = signal(-1);
  focusedValueAxisId = signal<string | null>(null);
  focusedSeriesId = signal<string | null>(null);
  filteredSeriesIds = signal<FilteredSeriesIds>({});

  // Measured size of the charts grid.
  private elementSize = createElementSize();
  gridWidth = this.elementSize.width;
  gridHeight = this.elementSize.height;

  ngOnInit(): void {
    // A share link restores the grid size, playback step and interval.
    const shared = this.consumeMultiShareState();
    const rows = shared ? shared.rows : defaultChartRows;
    const cols = shared ? shared.cols : defaultChartCols;
    const rate = shared ? shared.interval : defaultRate;
    this.chartRows.set(rows);
    this.chartCols.set(cols);
    this.rate.set(rate);
    const mochartDemoConfig = buildMochartDemoConfig(this.demoObject.config);
    this.mochartDemoConfig.set(mochartDemoConfig);
    const data = this.demoObject.data;
    this.data.set(data);
    const dataCount = data.length;
    this.dataCount.set(dataCount);
    this.sliceIds.set(this.computeSliceIds(mochartDemoConfig));
    // A shared step seeks the playback position; otherwise start on the full
    // set (pie mode starts at step 0 — the grid's staggered initial view).
    const cycle = this.stepCycle();
    const currentDataCount = shared !== null && cycle > 0
      ? ((Math.round(shared.step) % cycle) + cycle) % cycle
      : this.resetStep();
    this.currentDataCount.set(currentDataCount);
    this.dataProviders.set(getDataProvidersForDataCount(data, rows * cols, currentDataCount));
    this.focusedCategoryIndices.set(this.dataProviders().map(() => -1));
  }

  private consumeMultiShareState(): MultiShareState | null {
    const shared = consumeShareState('multi');
    return shared !== null && shared.mode === 'multi' ? shared : null;
  }

  private computeSliceIds(mochartDemoConfig: MochartDemoConfig): string[] {
    return mochartDemoConfig.pieMode ? getPieSlices(mochartDemoConfig.mochartConfig).map(slice => slice.id) : [];
  }

  private stepCycle(): number {
    return this.mochartDemoConfig()!.pieMode ? getPieStepCycle(this.sliceIds()) : this.dataCount();
  }

  private resetStep(): number {
    return this.mochartDemoConfig()!.pieMode ? 0 : this.dataCount();
  }

  private getChartContainers(): Element[] {
    const grid = this.gridElement?.nativeElement;
    return grid ? Array.from(grid.querySelectorAll('.multi-mochart-chart')) : [];
  }

  onExportPng = (): void => {
    const containers = this.getChartContainers();
    if (containers.length > 0) {
      void exportChartsPNG(containers, { cols: this.chartCols(), ...getChartExportOptions() });
    }
  };

  onExportSvg = (): void => {
    const containers = this.getChartContainers();
    if (containers.length > 0) {
      exportChartsSVG(containers, { cols: this.chartCols(), ...getChartExportOptions() });
    }
  };

  getShareState = (): ShareState => ({
    mode: 'multi', rows: this.chartRows(), cols: this.chartCols(), step: this.currentDataCount(), interval: this.rate()
  });

  ngAfterViewInit(): void {
    this.elementSize.observe(this.gridElement.nativeElement);
  }

  private initFocusAndFiltered(): void {
    this.focusedCategoryIndex.set(-1);
    this.focusedValueAxisId.set(null);
    this.focusedSeriesId.set(null);
    this.filteredSeriesIds.set({});
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (Object.values(changes).some(change => change.firstChange)) {
      return;
    }
    if (changes['demoObject']) {
      this.mochartDemoConfig.set(buildMochartDemoConfig(this.demoObject.config));
      this.initFocusAndFiltered();
      this.playing.set(false);
      this.data.set(this.demoObject.data);
      this.dataCount.set(this.data().length);
      this.sliceIds.set(this.computeSliceIds(this.mochartDemoConfig()!));
      this.currentDataCount.set(this.resetStep());
      this.dataProviders.set(getDataProvidersForDataCount(this.data(), this.chartRows() * this.chartCols(), this.currentDataCount()));
      this.focusedCategoryIndices.set(this.dataProviders().map(() => -1));
    }
    if (changes['active']) {
      this.onStopClick();
    }
  }

  onRateChange = (nextRate: number): void => {
    this.rate.set(nextRate);
  };

  onRowsChange = (nextChartRows: number): void => {
    this.chartRows.set(nextChartRows);
    this.currentDataCount.set(this.resetStep());
    this.dataProviders.set(getDataProvidersForDataCount(this.data(), this.chartRows() * this.chartCols(), this.currentDataCount()));
    this.focusedCategoryIndices.set(this.getFocusedCategoryIndices(this.dataProviders()));
  };

  onColsChange = (nextChartCols: number): void => {
    this.chartCols.set(nextChartCols);
    this.currentDataCount.set(this.resetStep());
    this.dataProviders.set(getDataProvidersForDataCount(this.data(), this.chartRows() * this.chartCols(), this.currentDataCount()));
    this.focusedCategoryIndices.set(this.getFocusedCategoryIndices(this.dataProviders()));
  };

  onStepBackwardClick = (): void => {
    const cycle = this.stepCycle();
    this.currentDataCount.set(this.mochartDemoConfig()!.pieMode
      ? (this.currentDataCount() - 1 + cycle) % cycle
      : cycle + (this.currentDataCount() - 1) % cycle);
    this.dataProviders.set(getDataProvidersForDataCount(this.data(), this.chartRows() * this.chartCols(), this.currentDataCount()));
    this.focusedCategoryIndices.set(this.getFocusedCategoryIndices(this.dataProviders()));
  };

  onStepForwardClick = (): void => {
    this.currentDataCount.set((this.currentDataCount() + 1) % this.stepCycle());
    this.dataProviders.set(getDataProvidersForDataCount(this.data(), this.chartRows() * this.chartCols(), this.currentDataCount()));
    this.focusedCategoryIndices.set(this.getFocusedCategoryIndices(this.dataProviders()));
  };

  private getFocusedCategoryIndices(nextDataProviders: ChartDataProviderLike[]): number[] {
    const { mochartConfig } = this.mochartDemoConfig()!;
    if (this.focusedCategoryIndex() >= 0) {
      const categoryValue = this.data()[this.focusedCategoryIndex()][mochartConfig.categoryAxis.property ?? ''];
      return this.getFocusedCategoryIndicesForValue(nextDataProviders, mochartConfig.categoryAxis.property ?? '', categoryValue);
    }
    else {
      return nextDataProviders.map(() => -1);
    }
  }

  private getFocusedCategoryIndicesForValue(nextDataProviders: ChartDataProviderLike[], categoryProperty: string, categoryValue: unknown): number[] {
    let count, i;
    return nextDataProviders.map(dataProvider => {
      let chartCategoryIndex = -1;
      const categoryValues = dataProvider.getPropertyValues(categoryProperty) ?? [];
      count = categoryValues.length;
      for (i = 0; i < count; i++) {
        if (categoryValues[i] === categoryValue) {
          chartCategoryIndex = i;
          break;
        }
      }
      return chartCategoryIndex;
    });
  }

  onPlayBackwardClick = (): void => {
    this.playing.set(true);
    this.intervalId = setInterval(this.onStepBackwardClick, this.rate());
  };

  onPlayForwardClick = (): void => {
    this.playing.set(true);
    this.intervalId = setInterval(this.onStepForwardClick, this.rate());
  };

  onStopClick = (): void => {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
    }
    this.intervalId = null;
    this.playing.set(false);
  };

  ngOnDestroy(): void {
    if (this.intervalId !== null) {
      clearInterval(this.intervalId);
      this.intervalId = null;
    }
    this.elementSize.disconnect();
  }

  onChartFocus(chartIndex: number, focusData: { focusedValueAxisId?: string | null; focusedSeriesId?: string | null; focusedCategoryIndex?: number }): void {
    const { focusedValueAxisId: valueAxisId, focusedSeriesId: seriesId } = focusData;
    let categoryIndex = focusData.focusedCategoryIndex;
    const { mochartConfig } = this.mochartDemoConfig()!;
    let nextFocusedCategoryIndices = this.focusedCategoryIndices();
    if (categoryIndex !== undefined && categoryIndex >= 0) {
      const categoryValue = (this.dataProviders()[chartIndex].getPropertyValues(mochartConfig.categoryAxis.property ?? '') ?? [])[categoryIndex];
      const count = this.data().length;
      for (let i = 0; i < count; i++) {
        if (this.data()[i][mochartConfig.categoryAxis.property ?? ''] === categoryValue) {
          categoryIndex = i;
          break;
        }
      }
      if (categoryIndex !== this.focusedCategoryIndex()) {
        nextFocusedCategoryIndices = this.getFocusedCategoryIndicesForValue(this.dataProviders(), mochartConfig.categoryAxis.property ?? '', categoryValue);
      }
    }
    else if (this.focusedCategoryIndex() >= 0) {
      nextFocusedCategoryIndices = this.dataProviders().map(() => -1);
    }
    if (categoryIndex !== undefined) {
      this.focusedCategoryIndex.set(categoryIndex);
    }
    if (valueAxisId !== undefined) {
      this.focusedValueAxisId.set(valueAxisId);
    }
    if (seriesId !== undefined) {
      this.focusedSeriesId.set(seriesId);
    }
    this.focusedCategoryIndices.set(nextFocusedCategoryIndices);
  }

  // Controlled focus for the chart at `chartIndex`; -1 (none) when the grid
  // has more charts than remapped indices so the input stays controlled.
  focusedCategoryIndexAt(chartIndex: number): number {
    return this.focusedCategoryIndices()[chartIndex] ?? -1;
  }

  // The chart reports the whole union it was shown; keep only the user delta.
  onSeriesFilter = (chartIndex: number, { filteredSeriesIds: reported }: { filteredSeriesIds: FilteredSeriesIds }): void => {
    this.filteredSeriesIds.set(applyReportedSeriesFilter(this.filteredSeriesIds(), this.chartFilteredSeriesIds(chartIndex), reported));
  };

  // Pie mode unions the stepper's per-chart filtering with the user's
  // legend filtering, so the legend stays interactive while stepping.
  chartFilteredSeriesIds(chartIndex: number): FilteredSeriesIds {
    return this.mochartDemoConfig()!.pieMode
      ? { ...this.filteredSeriesIds(), ...getPieStepFilteredIds(this.sliceIds(), chartIndex, this.currentDataCount()) }
      : this.filteredSeriesIds();
  }

  get chartWidth(): number {
    return Math.floor((this.gridWidth() - scrollWidthOffset) / this.chartCols());
  }

  get chartHeight(): number {
    return Math.floor(this.gridHeight() / this.chartRows());
  }
}
