// packages/mochart-demo-angular/src/components/single/chart-tab.ts
import { Component, ElementRef, Input, ViewChild, signal } from '@angular/core';
import type { AfterViewInit, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';

import { hasConfigStructureChange } from '@mochart/core';

import { buildMochartDemoConfig, getDemoTabPanelAttrs } from '@mochart/demo-common';

import { EditableChart } from './editable-chart';
import { createElementSize } from '../misc/element-size';

import type { DemoConfig, DataObject, MochartDemoConfig, FocusData, FilteredSeriesIds } from '../../types';

const minChartWidthForSecondChart = 480;
const scrollWidthOffset = 20;
const defaultChartCount = 1;

@Component({
  selector: 'app-chart-tab',
  imports: [EditableChart],
  styles: [':host { display: contents; }'],
  template: `
    <div #container [id]="panelAttrs.id" [attr.role]="panelAttrs.role" [attr.aria-labelledby]="panelAttrs['aria-labelledby']"
         [class]="'mochart-demo-tab-container demo-layout-row chart' + (active ? ' active' : '')" [attr.inert]="active ? null : ''">
      <div class="editable-charts-sizer">
        <div class="editable-charts">
          @if (mochartDemoConfig() && width() > 0) {
            @for (i of chartIndexes; track i) {
              <app-editable-chart [chartCount]="chartCount()" [showChartCountControls]="allowedChartCount > 1 && i === 1" [showShareButton]="i === 1"
                                  [width]="chartWidth" [mochartDemoConfig]="mochartDemoConfig()!" [data]="data ?? []" [dataError]="dataError"
                                  [isActive]="active" [filteredSeriesIds]="filteredSeriesIds()" [focusedCategoryIndex]="focusedCategoryIndex()"
                                  [focusedValueAxisId]="focusedValueAxisId()" [focusedSeriesId]="focusedSeriesId()" [onChartCountToggle]="onChartCountToggle"
                                  [onFocus]="onFocus" [onSeriesFilter]="onSeriesFilter" />
            }
          }
        </div>
      </div>
    </div>
  `
})
export class ChartTab implements OnInit, OnChanges, AfterViewInit, OnDestroy {
  readonly panelAttrs = getDemoTabPanelAttrs('chart');

  @Input() config: DemoConfig | null = null;
  @Input() data: DataObject[] | null = null;
  @Input() dataError: string | boolean | null = false;
  @Input() active = false;

  @ViewChild('container', { static: true }) containerElement!: ElementRef<HTMLDivElement>;

  // Measured width of the tab.
  private elementSize = createElementSize();
  width = this.elementSize.width;

  chartCount = signal(defaultChartCount);
  focusedValueAxisId = signal<string | null>(null);
  focusedSeriesId = signal<string | null>(null);
  focusedCategoryIndex = signal(-1);
  filteredSeriesIds = signal<FilteredSeriesIds>({});
  mochartDemoConfig = signal<MochartDemoConfig | null>(null);

  ngOnInit(): void {
    this.mochartDemoConfig.set(this.config ? buildMochartDemoConfig(this.config) : null);
  }

  ngAfterViewInit(): void {
    this.elementSize.observe(this.containerElement.nativeElement);
  }

  ngOnDestroy(): void {
    this.elementSize.disconnect();
  }

  private resetFocusAndFiltered(): void {
    this.focusedValueAxisId.set(null);
    this.focusedSeriesId.set(null);
    this.focusedCategoryIndex.set(-1);
    this.filteredSeriesIds.set({});
  }

  // Mirror the react lifecycle: a config change rebuilds the demo config and
  // resets focus/filter state when the structure changed (or on data errors);
  // a data change remaps the focused category index onto the new data.
  ngOnChanges(changes: SimpleChanges): void {
    const configChange = changes['config'];
    const dataChange = changes['data'];
    const dataErrorChange = changes['dataError'];
    if (!configChange && !dataChange && !dataErrorChange) {
      return;
    }
    if ([configChange, dataChange, dataErrorChange].some(change => change?.firstChange)) {
      return;
    }
    let configChanged = false;
    if (configChange) {
      const nextDemoConfig = this.config ? buildMochartDemoConfig(this.config) : null;
      const currentDemoConfig = this.mochartDemoConfig();
      if (nextDemoConfig && currentDemoConfig) {
        configChanged = hasConfigStructureChange(currentDemoConfig.mochartConfig, nextDemoConfig.mochartConfig);
      }
      this.mochartDemoConfig.set(nextDemoConfig);
    }
    if (this.dataError || configChanged) {
      this.resetFocusAndFiltered();
    }
    else if (dataChange) {
      const previousData = dataChange.previousValue as DataObject[] | null;
      const previousDataError = dataErrorChange ? dataErrorChange.previousValue : this.dataError;
      const { configValidation, mochartConfig } = this.mochartDemoConfig() ?? {};
      const valid = configValidation?.valid ?? false;
      if (!previousDataError && previousData && this.data && valid && mochartConfig) {
        if (this.focusedCategoryIndex() >= 0) {
          const property = mochartConfig.categoryAxis.property ?? '';
          const categoryValue = previousData[this.focusedCategoryIndex()][property];
          let newFocusedCategoryIndex = -1;
          const count = this.data.length;
          for (let i = 0; i < count; i++) {
            if (this.data[i][property] === categoryValue) {
              newFocusedCategoryIndex = i;
              break;
            }
          }
          this.focusedCategoryIndex.set(newFocusedCategoryIndex);
        }
      }
      else {
        this.resetFocusAndFiltered();
      }
    }
  }

  onFocus = (focusData: FocusData = {}): void => {
    const { valueAxisId, seriesId, categoryIndex } = focusData;
    if (valueAxisId !== undefined) {
      this.focusedValueAxisId.set(valueAxisId);
    }
    if (seriesId !== undefined) {
      this.focusedSeriesId.set(seriesId);
    }
    if (categoryIndex !== undefined) {
      this.focusedCategoryIndex.set(categoryIndex);
    }
  };

  // The chart owns filter toggling now and reports the whole map.
  onSeriesFilter = ({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }): void => {
    this.filteredSeriesIds.set({ ...nextFilteredSeriesIds });
  };

  onChartCountToggle = (): void => {
    this.chartCount.set(this.chartCount() === 1 ? 2 : 1);
  };

  get allowedChartCount(): number {
    return Math.floor(this.width() / 2) > minChartWidthForSecondChart ? 2 : 1;
  }

  get adjustedChartCount(): number {
    return Math.min(this.chartCount(), this.allowedChartCount);
  }

  get chartWidth(): number {
    return Math.floor((this.width() - scrollWidthOffset) / this.adjustedChartCount);
  }

  get chartIndexes(): number[] {
    return Array.from({ length: this.adjustedChartCount }, (_, index) => index + 1);
  }
}

// packages/mochart-demo-lit/src/components/single/chart-tab.ts
import { html } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import { ref } from 'lit/directives/ref.js';
import type { PropertyValues } from 'lit';

import { hasConfigStructureChange } from '@mochart/core';

import { buildMochartDemoConfig, getDemoTabPanelAttrs } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';
import { ElementSizeController } from '../misc/ElementSizeController';
import './editable-chart';

import type { DemoConfig, DataObject, MochartDemoConfig, FocusData, FilteredSeriesIds } from '../../types';

const minChartWidthForSecondChart = 480;
const scrollWidthOffset = 20;
const defaultChartCount = 1;

const panelAttrs = getDemoTabPanelAttrs('chart');

@customElement('chart-tab')
export class ChartTab extends LightElement {
  @property({ attribute: false }) config: DemoConfig | null = null;
  @property({ attribute: false }) data: DataObject[] | null = null;
  @property({ attribute: false }) dataError: string | boolean | null = false;
  @property({ attribute: false }) active = false;

  // Measured width of the tab.
  private size = new ElementSizeController(this);

  @state() private chartCount = defaultChartCount;
  @state() private focusedValueAxisId: string | null = null;
  @state() private focusedSeriesId: string | null = null;
  @state() private focusedCategoryIndex = -1;
  @state() private filteredSeriesIds: FilteredSeriesIds = {};
  @state() private mochartDemoConfig: MochartDemoConfig | null = null;

  private resetFocusAndFiltered(): void {
    this.focusedValueAxisId = null;
    this.focusedSeriesId = null;
    this.focusedCategoryIndex = -1;
    this.filteredSeriesIds = {};
  }

  // Mirror the react lifecycle: a config change rebuilds the demo config and
  // resets focus/filter state when the structure changed (or on data errors);
  // a data change remaps the focused category index onto the new data.
  override willUpdate(changed: PropertyValues<this>): void {
    if (!this.hasUpdated) {
      this.mochartDemoConfig = this.config ? buildMochartDemoConfig(this.config) : null;
      return;
    }
    if (!changed.has('config') && !changed.has('data') && !changed.has('dataError')) {
      return;
    }
    const previousConfig = changed.has('config') ? (changed.get('config') as DemoConfig | null) : this.config;
    const previousData = changed.has('data') ? (changed.get('data') as DataObject[] | null) : this.data;
    const previousDataError = changed.has('dataError') ? (changed.get('dataError') as string | boolean | null) : this.dataError;
    let configChanged = false;
    if (this.config !== previousConfig) {
      const nextDemoConfig = this.config ? buildMochartDemoConfig(this.config) : null;
      if (nextDemoConfig && this.mochartDemoConfig) {
        configChanged = hasConfigStructureChange(this.mochartDemoConfig.mochartConfig, nextDemoConfig.mochartConfig);
      }
      this.mochartDemoConfig = nextDemoConfig;
    }
    if (this.dataError || configChanged) {
      this.resetFocusAndFiltered();
    }
    else if (this.data !== previousData) {
      const { configValidation, mochartConfig } = this.mochartDemoConfig ?? {};
      const valid = configValidation?.valid ?? false;
      if (!previousDataError && previousData && this.data && valid && mochartConfig) {
        if (this.focusedCategoryIndex >= 0) {
          const property = mochartConfig.categoryAxis.property ?? '';
          const categoryValue = previousData[this.focusedCategoryIndex][property];
          let newFocusedCategoryIndex = -1;
          const count = this.data.length;
          for (let i = 0; i < count; i++) {
            if (this.data[i][property] === categoryValue) {
              newFocusedCategoryIndex = i;
              break;
            }
          }
          this.focusedCategoryIndex = newFocusedCategoryIndex;
        }
      }
      else {
        this.resetFocusAndFiltered();
      }
    }
  }

  private onFocus = (focusData: FocusData = {}): void => {
    const { valueAxisId, seriesId, categoryIndex } = focusData;
    if (valueAxisId !== undefined) {
      this.focusedValueAxisId = valueAxisId;
    }
    if (seriesId !== undefined) {
      this.focusedSeriesId = seriesId;
    }
    if (categoryIndex !== undefined) {
      this.focusedCategoryIndex = categoryIndex;
    }
  };

  // The chart owns filter toggling now and reports the whole map.
  private onSeriesFilter = ({ filteredSeriesIds: nextFilteredSeriesIds }: { filteredSeriesIds: FilteredSeriesIds }): void => {
    this.filteredSeriesIds = { ...nextFilteredSeriesIds };
  };

  private onChartCountToggle = (): void => {
    this.chartCount = this.chartCount === 1 ? 2 : 1;
  };

  override render(): unknown {
    const width = this.size.width;
    const allowedChartCount = Math.floor(width / 2) > minChartWidthForSecondChart ? 2 : 1;
    const adjustedChartCount = Math.min(this.chartCount, allowedChartCount);
    const chartWidth = Math.floor((width - scrollWidthOffset) / adjustedChartCount);
    const chartIndices = Array.from({ length: adjustedChartCount }, (_unused, index) => index + 1);
    return html`<div ${ref(this.size.attach)} id=${panelAttrs.id} role=${panelAttrs.role} aria-labelledby=${panelAttrs['aria-labelledby']}
        class=${'mochart-demo-tab-container demo-layout-row chart' + (this.active ? ' active' : '')} ?inert=${!this.active}>
      <div class="editable-charts-sizer">
        <div class="editable-charts">
          ${this.mochartDemoConfig && width > 0
            ? chartIndices.map(i => html`<editable-chart
                .chartCount=${this.chartCount} .showChartCountControls=${allowedChartCount > 1 && i === 1} .showShareButton=${i === 1}
                .width=${chartWidth} .mochartDemoConfig=${this.mochartDemoConfig!} .data=${this.data ?? []} .dataError=${this.dataError}
                .isActive=${this.active} .filteredSeriesIds=${this.filteredSeriesIds} .focusedCategoryIndex=${this.focusedCategoryIndex}
                .focusedValueAxisId=${this.focusedValueAxisId} .focusedSeriesId=${this.focusedSeriesId} .onChartCountToggle=${this.onChartCountToggle}
                .onFocus=${this.onFocus} .onSeriesFilter=${this.onSeriesFilter}></editable-chart>`)
            : null}
        </div>
      </div>
    </div>`;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'chart-tab': ChartTab;
  }
}
