// packages/mochart-demo-vue/src/components/single/ConfigTab.vue
<script setup lang="ts">
import { computed, h, ref, shallowRef, watch } from 'vue';

import { buildMochartDemoConfig, controlsMenuPlacement, copyDemoConfig, demoConfigFromText, demoText, formatMochartDemoConfig, getDemoTabPanelAttrs, getJsonError, getJsonErrorMessage, getReferenceSectionIds, isConfigSectionActive, parseConfigFromText, parseJson, slowAnimationConfig, toggleConfigFromText, toggleConfigProperty, toggleConfigSection } from '@mochart/demo-common';

import JsonEditorContent from '../misc/JsonEditorContent.vue';
import ButtonWithTooltip from '../misc/ButtonWithTooltip.vue';
import DocsLinks from '../misc/DocsLinks.vue';
import Icon from '../misc/Icon.vue';
import OverflowMenu from '../misc/OverflowMenu.vue';
import { usePhoneViewport } from '../misc/usePhoneViewport';

import type { DemoConfigView } from '@mochart/demo-common';
import type { DemoConfig } from '../../types';

interface Props {
  active?: boolean;
  config: DemoConfig;
  onConfigChange: (config: DemoConfig) => void;
  onConfigReset: () => void;
}

const props = withDefaults(defineProps<Props>(), {
  active: false
});

const showDefaults = ref(false);
const errorMessage = ref<string | null>(null);
const mochartDemoConfig = shallowRef(buildMochartDemoConfig(props.config));
const demoConfig = shallowRef(copyDemoConfig(mochartDemoConfig.value));
const configText = ref(formatMochartDemoConfig(demoConfig.value, false));

watch(() => props.config, (nextConfig) => {
  mochartDemoConfig.value = buildMochartDemoConfig(nextConfig);
  demoConfig.value = copyDemoConfig(mochartDemoConfig.value);
  configText.value = formatMochartDemoConfig(demoConfig.value, showDefaults.value);
});

// demoConfig tracks the text, so the Invert/Slow states and reference links follow unapplied edits.
function onTextChange(nextConfigText: string) {
  configText.value = nextConfigText;
  demoConfig.value = demoConfigFromText(nextConfigText, demoConfig.value);
  errorMessage.value = null;
}

function resetConfig() {
  props.onConfigReset();
}

function updateShowDefaults(nextShowDefaults: boolean) {
  try {
    const newConfig = parseJson(configText.value) as DemoConfig;
    const newMochartDemoConfig = buildMochartDemoConfig(newConfig);
    const { configValidation } = newMochartDemoConfig;
    const { valid } = configValidation;
    if (valid) {
      showDefaults.value = nextShowDefaults;
      configText.value = formatMochartDemoConfig(newMochartDemoConfig, nextShowDefaults);
      errorMessage.value = null;
    }
    else {
      const { errors, warnings } = configValidation;
      if (errors.length > 0) {
        console.warn('errors: ', errors);
      }
      if (warnings.length > 0) {
        console.warn('warnings: ', warnings);
      }
      errorMessage.value = demoText.errors.invalidChartConfig;
    }
  }
  catch (error) {
    console.warn('Invalid Chart Config JSON: ' + configText.value);
    errorMessage.value = getJsonErrorMessage(error);
  }
}

function toggleConfigDefaults() {
  updateShowDefaults(!showDefaults.value);
}

// Toggle against the current text (the Defaults toggle's pattern), so
// unapplied textarea edits survive the toggle instead of being overwritten.
function applyConfigToggle(transform: (current: DemoConfigView) => DemoConfigView) {
  const result = toggleConfigFromText(configText.value, showDefaults.value, transform);
  if (result.error !== null) {
    errorMessage.value = result.error;
  }
  else {
    demoConfig.value = result.demoConfig;
    configText.value = result.text;
    errorMessage.value = null;
  }
}

function toggleConfigInverted() {
  applyConfigToggle(current => toggleConfigProperty(current, 'plot', 'inverted', true));
}

function toggleConfigAnimationSlow() {
  applyConfigToggle(current => toggleConfigSection(mochartDemoConfig.value, current, 'animation', slowAnimationConfig));
}

function applyConfig() {
  const { config, error } = parseConfigFromText(configText.value);
  errorMessage.value = error;
  if (config !== null) {
    props.onConfigChange(config);
  }
}

const inverted = computed(() => demoConfig.value.configWithDefaults.plot.inverted);
const invertedIcon = computed(() => inverted.value ? 'chart-bar' : 'chart-column');
const slow = computed(() => isConfigSectionActive(demoConfig.value, 'animation', slowAnimationConfig));
const slowIcon = computed(() => slow.value ? 'hourglass' : 'hourglass-end');

// Live JSON validity: disables Apply and shows an inline hint while the
// editor holds unparseable text.
const jsonError = computed(() => getJsonError(configText.value));
const footerError = computed(() => jsonError.value ?? errorMessage.value);

// ---------------------------------------------------------------------------
// The phone fold. Apply stays beside the editor it applies, and the
// `role="alert"` error span stays inline, because a message that has to be read
// cannot live behind a tap. Everything else, including the reference links,
// goes to the `⋯` menu. Each foldable control is a functional component
// rendered in exactly one of the two places (see OverflowMenu.vue).
// ---------------------------------------------------------------------------
const isPhone = usePhoneViewport();
const hasDocsLinks = computed(() => getReferenceSectionIds(demoConfig.value.configWithoutDefaults).length > 0);
const footerElement = ref<HTMLElement | null>(null);
const getFooterAnchor = () => footerElement.value;
const editorComponent = ref<InstanceType<typeof JsonEditorContent> | null>(null);

const iconChild = (name: string) => () => h(Icon, { size: 'lg', fixedWidth: true, name });

const ResetButton = () => h(ButtonWithTooltip, {
  id: 'config-reset', label: demoText.configTab.reset.label, tooltipText: demoText.configTab.reset.tooltip,
  tooltipPlacement: 'top-start', onClick: resetConfig, 'aria-label': demoText.configTab.reset.aria
}, iconChild('arrow-rotate-left'));

const DefaultsButton = () => h(ButtonWithTooltip, {
  id: 'config-defaults', label: demoText.configTab.defaults.label, pressed: showDefaults.value,
  tooltipText: demoText.configTab.defaults.tooltip, tooltipPlacement: 'top-start',
  onClick: toggleConfigDefaults, 'aria-label': demoText.configTab.defaults.aria
}, iconChild(showDefaults.value ? 'eye' : 'eye-slash'));

const InvertedButton = () => h(ButtonWithTooltip, {
  id: 'config-inverted', label: demoText.configTab.invert.label, pressed: !!inverted.value,
  tooltipText: demoText.configTab.invert.tooltip, tooltipPlacement: 'top-start',
  onClick: toggleConfigInverted, 'aria-label': demoText.configTab.invert.aria
}, iconChild(invertedIcon.value));

const SlowButton = () => h(ButtonWithTooltip, {
  id: 'config-animate-slow', label: demoText.configTab.slow.label, pressed: slow.value,
  tooltipText: demoText.configTab.slow.tooltip, tooltipPlacement: 'top-start',
  onClick: toggleConfigAnimationSlow, 'aria-label': demoText.configTab.slow.aria
}, iconChild(slowIcon.value));

const FormatButton = () => h(ButtonWithTooltip, {
  id: 'config-format', label: demoText.configTab.format.label, disabled: jsonError.value !== null,
  tooltipText: demoText.configTab.format.tooltip, tooltipPlacement: 'top-start',
  onClick: () => { editorComponent.value?.format(); }, 'aria-label': demoText.configTab.format.aria
}, iconChild('indent'));

const ApplyButton = () => h(ButtonWithTooltip, {
  id: 'config-apply', label: demoText.configTab.apply.label, disabled: jsonError.value !== null,
  tooltipText: demoText.configTab.apply.tooltip, tooltipPlacement: 'top-start',
  onClick: applyConfig, 'aria-label': demoText.configTab.apply.aria
}, iconChild('check'));

const panelAttrs = getDemoTabPanelAttrs('config');
</script>

<template>
  <div v-bind="panelAttrs" :class="'mochart-demo-tab-container demo-layout-col config' + (props.active ? ' active' : '')" :inert="!props.active">
    <div class="mochart-demo-tab-content">
      <JsonEditorContent ref="editorComponent" :value="configText" :ariaLabel="demoText.configTab.editorAria"
                         :format-on-set="true" :mochart-support="true" :on-change="onTextChange" />
    </div>
    <div class="mochart-demo-tab-footer" ref="footerElement">
      <div class="demo-toolbar">
        <template v-if="isPhone">
          <ApplyButton />
          <!-- `.editor`, not `.chart`: what folds here edits the JSON, and
               "more chart controls" would tell a screen-reader user the wrong
               thing. Anchored to the full-width footer, because the trigger sits
               mid-row, left of an error span that comes and goes. -->
          <OverflowMenu :text="demoText.overflowMenu.editor"
                        :placement="controlsMenuPlacement"
                        :get-anchor="getFooterAnchor"
                        :active="props.active">
            <div class="demo-btn-group"><ResetButton /><DefaultsButton /><InvertedButton /><SlowButton /><FormatButton /></div>
            <template v-if="hasDocsLinks">
              <div class="demo-menu-divider"></div>
              <DocsLinks :config="demoConfig.configWithoutDefaults" />
            </template>
          </OverflowMenu>
        </template>
        <template v-else>
          <ResetButton />
          <DefaultsButton />
          <InvertedButton />
          <SlowButton />
          <FormatButton />
          <ApplyButton />
        </template>
        <span v-if="footerError" class="mochart-demo-footer-error" role="alert">{{ footerError }}</span>
      </div>
      <DocsLinks v-if="!isPhone" :config="demoConfig.configWithoutDefaults" />
    </div>
  </div>
</template>

// packages/mochart-demo-lit/src/components/single/config-tab.ts
import { html, nothing } from 'lit';
import { customElement, property, state } from 'lit/decorators.js';
import type { PropertyValues } from 'lit';

import { buildMochartDemoConfig, controlsMenuPlacement, copyDemoConfig, demoConfigFromText, demoText, formatMochartDemoConfig, getDemoTabPanelAttrs, getJsonError, getJsonErrorMessage, isConfigSectionActive, parseConfigFromText, parseJson, slowAnimationConfig, toggleConfigFromText, toggleConfigProperty, toggleConfigSection } from '@mochart/demo-common';

import type { DemoConfigView } from '@mochart/demo-common';

import { LightElement } from '../misc/LightElement';
import { PhoneViewportController } from '../misc/PhoneViewportController';
import { buttonWithTooltip, docsLinks, icon } from '../misc/templates';
import '../misc/json-editor-content';
import '../misc/overflow-menu';

import type { DemoConfig, MochartDemoConfig } from '../../types';

const panelAttrs = getDemoTabPanelAttrs('config');

@customElement('config-tab')
export class ConfigTab extends LightElement {
  @property({ attribute: false }) active = false;
  @property({ attribute: false }) config!: DemoConfig;
  @property({ attribute: false }) onConfigChange!: (config: DemoConfig) => void;
  @property({ attribute: false }) onConfigReset!: () => void;

  @state() private showDefaults = false;
  @state() private mochartDemoConfig!: MochartDemoConfig;
  @state() private demoConfig!: DemoConfigView;
  @state() private configText = '';
  @state() private errorMessage: string | null = null;

  private viewport = new PhoneViewportController(this);

  override willUpdate(changed: PropertyValues<this>): void {
    if (changed.has('config')) {
      this.mochartDemoConfig = buildMochartDemoConfig(this.config);
      this.demoConfig = copyDemoConfig(this.mochartDemoConfig);
      this.configText = formatMochartDemoConfig(this.demoConfig, this.hasUpdated ? this.showDefaults : false);
    }
  }

  // demoConfig tracks the text, so the Invert/Slow states and reference links follow unapplied edits.
  private onTextChange = (nextConfigText: string): void => {
    this.configText = nextConfigText;
    this.demoConfig = demoConfigFromText(nextConfigText, this.demoConfig);
    this.errorMessage = null;
  };

  private resetConfig = (): void => {
    this.onConfigReset();
  };

  private updateShowDefaults(nextShowDefaults: boolean): void {
    try {
      const newConfig = parseJson(this.configText) as DemoConfig;
      const newMochartDemoConfig = buildMochartDemoConfig(newConfig);
      const { configValidation } = newMochartDemoConfig;
      const { valid } = configValidation;
      if (valid) {
        this.showDefaults = nextShowDefaults;
        this.configText = formatMochartDemoConfig(newMochartDemoConfig, nextShowDefaults);
        this.errorMessage = null;
      }
      else {
        const { errors, warnings } = configValidation;
        if (errors.length > 0) {
          console.warn('errors: ', errors);
        }
        if (warnings.length > 0) {
          console.warn('warnings: ', warnings);
        }
        this.errorMessage = demoText.errors.invalidChartConfig;
      }
    }
    catch (error) {
      console.warn('Invalid Chart Config JSON: ' + this.configText);
      this.errorMessage = getJsonErrorMessage(error);
    }
  }

  private toggleConfigDefaults = (): void => {
    this.updateShowDefaults(!this.showDefaults);
  };

  // Toggle against the current text (the Defaults toggle's pattern), so
  // unapplied textarea edits survive the toggle instead of being overwritten.
  private applyConfigToggle(transform: (current: DemoConfigView) => DemoConfigView): void {
    const result = toggleConfigFromText(this.configText, this.showDefaults, transform);
    if (result.error !== null) {
      this.errorMessage = result.error;
    }
    else {
      this.demoConfig = result.demoConfig;
      this.configText = result.text;
      this.errorMessage = null;
    }
  }

  private toggleConfigInverted = (): void => {
    this.applyConfigToggle(current => toggleConfigProperty(current, 'plot', 'inverted', true));
  };

  private toggleConfigAnimationSlow = (): void => {
    this.applyConfigToggle(current => toggleConfigSection(this.mochartDemoConfig, current, 'animation', slowAnimationConfig));
  };

  private applyConfig = (): void => {
    const { config, error } = parseConfigFromText(this.configText);
    this.errorMessage = error;
    if (config !== null) {
      this.onConfigChange(config);
    }
  };

  private formatConfig = (): void => {
    this.querySelector('json-editor-content')?.format();
  };

  // Live JSON validity: disables Apply and shows an inline hint while the
  // editor holds unparseable text.
  private get jsonError(): string | null {
    return getJsonError(this.configText);
  }

  override render(): unknown {
    const inverted = this.demoConfig.configWithDefaults.plot.inverted;
    const invertedIcon = inverted ? 'chart-bar' : 'chart-column';
    const slow = isConfigSectionActive(this.demoConfig, 'animation', slowAnimationConfig);
    const slowIcon = slow ? 'hourglass' : 'hourglass-end';
    const jsonError = this.jsonError;
    const footerError = jsonError ?? this.errorMessage;
    // The phone fold. Apply stays beside the editor it applies, and the
    // `role="alert"` error span stays inline, because a message that has to be read
    // cannot live behind a tap. Everything else, including the reference
    // links, goes to the `⋯` menu.
    const folded = this.viewport.isPhone;
    const resetButton = buttonWithTooltip(
      { id: 'config-reset', label: demoText.configTab.reset.label, tooltipText: demoText.configTab.reset.tooltip, tooltipPlacement: 'top-start', onClick: this.resetConfig, ariaLabel: demoText.configTab.reset.aria },
      icon({ size: 'lg', fixedWidth: true, name: 'arrow-rotate-left' })
    );
    const defaultsButton = buttonWithTooltip(
      { id: 'config-defaults', label: demoText.configTab.defaults.label, pressed: this.showDefaults, tooltipText: demoText.configTab.defaults.tooltip, tooltipPlacement: 'top-start', onClick: this.toggleConfigDefaults, ariaLabel: demoText.configTab.defaults.aria },
      icon({ size: 'lg', fixedWidth: true, name: this.showDefaults ? 'eye' : 'eye-slash' })
    );
    const invertedButton = buttonWithTooltip(
      { id: 'config-inverted', label: demoText.configTab.invert.label, pressed: !!inverted, tooltipText: demoText.configTab.invert.tooltip, tooltipPlacement: 'top-start', onClick: this.toggleConfigInverted, ariaLabel: demoText.configTab.invert.aria },
      icon({ size: 'lg', fixedWidth: true, name: invertedIcon })
    );
    const slowButton = buttonWithTooltip(
      { id: 'config-animate-slow', label: demoText.configTab.slow.label, pressed: slow, tooltipText: demoText.configTab.slow.tooltip, tooltipPlacement: 'top-start', onClick: this.toggleConfigAnimationSlow, ariaLabel: demoText.configTab.slow.aria },
      icon({ size: 'lg', fixedWidth: true, name: slowIcon })
    );
    const formatButton = buttonWithTooltip(
      { id: 'config-format', label: demoText.configTab.format.label, disabled: jsonError !== null, tooltipText: demoText.configTab.format.tooltip, tooltipPlacement: 'top-start', onClick: this.formatConfig, ariaLabel: demoText.configTab.format.aria },
      icon({ size: 'lg', fixedWidth: true, name: 'indent' })
    );
    const applyButton = buttonWithTooltip(
      { id: 'config-apply', label: demoText.configTab.apply.label, disabled: jsonError !== null, tooltipText: demoText.configTab.apply.tooltip, tooltipPlacement: 'top-start', onClick: this.applyConfig, ariaLabel: demoText.configTab.apply.aria },
      icon({ size: 'lg', fixedWidth: true, name: 'check' })
    );
    const links = docsLinks(this.demoConfig.configWithoutDefaults);
    return html`<div id=${panelAttrs.id} role=${panelAttrs.role} aria-labelledby=${panelAttrs['aria-labelledby']}
        class=${'mochart-demo-tab-container demo-layout-col config' + (this.active ? ' active' : '')} ?inert=${!this.active}>
      <div class="mochart-demo-tab-content">
        <json-editor-content .value=${this.configText} .ariaLabelText=${demoText.configTab.editorAria}
          .formatOnSet=${true} .mochartSupport=${true} .onChange=${this.onTextChange}></json-editor-content>
      </div>
      <div class="mochart-demo-tab-footer">
        <div class="demo-toolbar">
          ${folded
            ? html`${applyButton}
              <!-- \`.editor\`, not \`.chart\`: what folds here edits the JSON,
                   and "more chart controls" would tell a screen-reader user
                   the wrong thing. Anchored to the full-width footer, because the
                   trigger sits mid-row, left of an error span that comes and
                   goes. -->
              <overflow-menu .text=${demoText.overflowMenu.editor} .placement=${controlsMenuPlacement}
                .getAnchor=${this.getFooterAnchor} .active=${this.active}
                .items=${() => html`<div class="demo-btn-group">${resetButton}${defaultsButton}${invertedButton}${slowButton}${formatButton}</div>
                  ${links === nothing ? nothing : html`<div class="demo-menu-divider"></div>${links}`}`}></overflow-menu>`
            : html`${resetButton}${defaultsButton}${invertedButton}${slowButton}${formatButton}${applyButton}`}
          ${footerError ? html`<span class="mochart-demo-footer-error" role="alert">${footerError}</span>` : nothing}
        </div>
        ${folded ? nothing : links}
      </div>
    </div>`;
  }

  private getFooterAnchor = (): HTMLElement | null => this.querySelector('.mochart-demo-tab-footer');
}

declare global {
  interface HTMLElementTagNameMap {
    'config-tab': ConfigTab;
  }
}
